package com.ibm.ioes.npd.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.util.ArrayList;
import java.util.Date;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

import com.ibm.ioes.npd.hibernate.beans.TmEmployee;
import com.ibm.ioes.npd.hibernate.beans.TmProductcategory;
import com.ibm.ioes.npd.hibernate.beans.TtrnProject;
import com.ibm.ioes.npd.utilities.PagingSorting;


/**
 * TmAppconfig generated by hbm2java
 */

public class PlrUploadingFormBean extends ActionForm  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int stageid;
	private String stagename;
	private int taskid;
	private String taskname;
	private Date plannedstartdate;
	private Date plannedenddate;
	private Date actualstartdate;
	private Date actualenddate;
	private String stakeholderrole;
	private String stakeholdername;
	private int delayindays;
	private String projectPlanId;
	
	private String searchProjectPlanName;
	private String searchStageName;
	private String searchTaskName;
	private String searchProjectId;
	
	private String dateFilter=null;
	private String fromDate=null;
	private String toDate=null;
	private String projectActionId;
	
	private String fileName;
	private String projectId;
	private String taskId;
	private String stageId;
	private String projectStatusFilter="-1"; //Default Value is -1 For All Projects
	private ArrayList<TmEmployee> lstEmployee;
	private String[] employeeId;
	private ArrayList<TtrnProject> lstProject;
	private String seachprojectId;
	private String sortBy=null;
	private String sortByOrder=null;  /*values : "increment" ,"decrement"  */	
	private String pageNumber="1";
	private String maxPageNumber=null;
	private String stakeholderidlist;
	private String hiddenReturnFlag;
	private FormFile attachment;
	private String searchLaunchPriority;
	private String isupload;
	private String userId;
	private String searchproject;
	private String roleid;

	private String rolename;
	private TmEmployee tmployee;
	private String ismapped;
	private String selectedRow;
	private String monthid;
	private ArrayList lstMonthYear;
	private String monthlabel;
	private String monthvalue;
	
	private ArrayList lstemployee;
	private String employeelabel;
	private String employeevalue;
	
	private int pageRecords;
	
	//private String pageNumber="1";
	//private String maxPageNumber=null;//getter setter
	//private String sortBy=null;
	//private String sortByOrder=null;  //getter setter
	
	private PagingSorting pagingSorting=null;
	private String plannedduration;

	public PlrUploadingFormBean()
	{
		System.err.println("in constructor");
		pagingSorting=new PagingSorting();
	}
	
	public Date getActualenddate() {
		return actualenddate;
	}
	public void setActualenddate(Date actualenddate) {
		this.actualenddate = actualenddate;
	}
	public Date getActualstartdate() {
		return actualstartdate;
	}
	public void setActualstartdate(Date actualstartdate) {
		this.actualstartdate = actualstartdate;
	}
	public int getDelayindays() {
		return delayindays;
	}
	public void setDelayindays(int delayindays) {
		this.delayindays = delayindays;
	}
	public Date getPlannedenddate() {
		return plannedenddate;
	}
	public void setPlannedenddate(Date plannedenddate) {
		this.plannedenddate = plannedenddate;
	}
	public Date getPlannedstartdate() {
		return plannedstartdate;
	}
	public void setPlannedstartdate(Date plannedstartdate) {
		this.plannedstartdate = plannedstartdate;
	}
	public int getStageid() {
		return stageid;
	}
	public void setStageid(int stageid) {
		this.stageid = stageid;
	}
	public String getStagename() {
		return stagename;
	}
	public void setStagename(String stagename) {
		this.stagename = stagename;
	}
	public String getStakeholdername() {
		return stakeholdername;
	}
	public void setStakeholdername(String stakeholdername) {
		this.stakeholdername = stakeholdername;
	}
	public String getStakeholderrole() {
		return stakeholderrole;
	}
	public void setStakeholderrole(String stakeholderrole) {
		this.stakeholderrole = stakeholderrole;
	}
	public int getTaskid() {
		return taskid;
	}
	public void setTaskid(int taskid) {
		this.taskid = taskid;
	}
	public String getTaskname() {
		return taskname;
	}
	public void setTaskname(String taskname) {
		this.taskname = taskname;
	}
	public static long getSerialVersionUID() {
		return serialVersionUID;
	}
	public PagingSorting getPagingSorting() {
		return pagingSorting;
	}
	public void setPagingSorting(PagingSorting pagingSorting) {
		this.pagingSorting = pagingSorting;
	}

	public String getSearchProjectPlanName() {
		return searchProjectPlanName;
	}

	public void setSearchProjectPlanName(String searchProjectPlanName) {
		this.searchProjectPlanName = searchProjectPlanName;
	}

	public String getSearchStageName() {
		return searchStageName;
	}

	public void setSearchStageName(String searchStageName) {
		this.searchStageName = searchStageName;
	}

	public String getProjectPlanId() {
		return projectPlanId;
	}

	public void setProjectPlanId(String projectPlanId) {
		this.projectPlanId = projectPlanId;
	}

	public String getSearchTaskName() {
		return searchTaskName;
	}

	public void setSearchTaskName(String searchTaskName) {
		this.searchTaskName = searchTaskName;
	}

	public String getDateFilter() {
		return dateFilter;
	}

	public void setDateFilter(String dateFilter) {
		this.dateFilter = dateFilter;
	}

	public String getFromDate() {
		return fromDate;
	}

	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	public String getToDate() {
		return toDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}

	public String getSearchProjectId() {
		return searchProjectId;
	}

	public void setSearchProjectId(String searchProjectId) {
		this.searchProjectId = searchProjectId;
	}

	public String getProjectActionId() {
		return projectActionId;
	}

	public void setProjectActionId(String projectActionId) {
		this.projectActionId = projectActionId;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getProjectStatusFilter() {
		return projectStatusFilter;
	}

	public void setProjectStatusFilter(String projectStatusFilter) {
		this.projectStatusFilter = projectStatusFilter;
	}

	public String getProjectId() {
		return projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getStageId() {
		return stageId;
	}

	public void setStageId(String stageId) {
		this.stageId = stageId;
	}

	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public ArrayList<TmEmployee> getLstEmployee() {
		return lstEmployee;
	}

	public void setLstEmployee(ArrayList<TmEmployee> lstEmployee) {
		this.lstEmployee = lstEmployee;
	}


	public ArrayList<TtrnProject> getLstProject() {
		return lstProject;
	}

	public void setLstProject(ArrayList<TtrnProject> lstProject) {
		this.lstProject = lstProject;
	}

	public String getSeachprojectId() {
		return seachprojectId;
	}

	public void setSeachprojectId(String seachprojectId) {
		this.seachprojectId = seachprojectId;
	}

	public String getSortBy() {
		return sortBy;
	}

	public void setSortBy(String sortBy) {
		this.sortBy = sortBy;
	}

	public String getSortByOrder() {
		return sortByOrder;
	}

	public void setSortByOrder(String sortByOrder) {
		this.sortByOrder = sortByOrder;
	}

	public String getMaxPageNumber() {
		return maxPageNumber;
	}

	public void setMaxPageNumber(String maxPageNumber) {
		this.maxPageNumber = maxPageNumber;
	}

	public String getPageNumber() {
		return pageNumber;
	}

	public void setPageNumber(String pageNumber) {
		this.pageNumber = pageNumber;
	}

	public String getStakeholderidlist() {
		return stakeholderidlist;
	}

	public void setStakeholderidlist(String stakeholderidlist) {
		this.stakeholderidlist = stakeholderidlist;
	}

	public String getPlannedduration() {
		return plannedduration;
	}

	public void setPlannedduration(String plannedduration) {
		this.plannedduration = plannedduration;
	}

	public String getHiddenReturnFlag() {
		return hiddenReturnFlag;
	}

	public void setHiddenReturnFlag(String hiddenReturnFlag) {
		this.hiddenReturnFlag = hiddenReturnFlag;
	}

	public String[] getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(String[] employeeId) {
		this.employeeId = employeeId;
	}

	public FormFile getAttachment() {
		return attachment;
	}

	public void setAttachment(FormFile attachment) {
		this.attachment = attachment;
	}

	public String getSearchLaunchPriority() {
		return searchLaunchPriority;
	}

	public void setSearchLaunchPriority(String searchLaunchPriority) {
		this.searchLaunchPriority = searchLaunchPriority;
	}

	public String getIsupload() {
		return isupload;
	}

	public void setIsupload(String isupload) {
		this.isupload = isupload;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getSearchproject() {
		return searchproject;
	}

	public void setSearchproject(String searchproject) {
		this.searchproject = searchproject;
	}

	public String getRoleid() {
		return roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getIsmapped() {
		return ismapped;
	}

	public void setIsmapped(String ismapped) {
		this.ismapped = ismapped;
	}

	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public TmEmployee getTmployee() {
		return tmployee;
	}

	public void setTmployee(TmEmployee tmployee) {
		this.tmployee = tmployee;
	}

	public String getSelectedRow() {
		return selectedRow;
	}

	public void setSelectedRow(String selectedRow) {
		this.selectedRow = selectedRow;
	}

	public String getMonthid() {
		return monthid;
	}

	public void setMonthid(String monthid) {
		this.monthid = monthid;
	}

	public String getMonthlabel() {
		return monthlabel;
	}

	public void setMonthlabel(String monthlabel) {
		this.monthlabel = monthlabel;
	}


	public ArrayList getLstMonthYear() {
		return lstMonthYear;
	}

	public void setLstMonthYear(ArrayList lstMonthYear) {
		this.lstMonthYear = lstMonthYear;
	}

	public String getMonthvalue() {
		return monthvalue;
	}

	public void setMonthvalue(String monthvalue) {
		this.monthvalue = monthvalue;
	}

	public String getEmployeelabel() {
		return employeelabel;
	}

	public void setEmployeelabel(String employeelabel) {
		this.employeelabel = employeelabel;
	}

	public String getEmployeevalue() {
		return employeevalue;
	}

	public void setEmployeevalue(String employeevalue) {
		this.employeevalue = employeevalue;
	}

	public ArrayList getLstemployee() {
		return lstemployee;
	}

	public void setLstemployee(ArrayList lstemployee) {
		this.lstemployee = lstemployee;
	}
	public int getPageRecords() {
		return pageRecords;
	}

	public void setPageRecords(int pageRecords) {
		this.pageRecords = pageRecords;
	}
	
	
}
