package com.ibm.ioes.npd.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.util.ArrayList;
import java.util.Date;

import org.apache.struts.action.ActionForm;

import com.ibm.ioes.npd.hibernate.beans.TtrnProject;
import com.ibm.ioes.npd.hibernate.beans.TtrnProjectassumptions;
import com.ibm.ioes.npd.hibernate.beans.TtrnProjecthierarchy;
import com.ibm.ioes.npd.hibernate.beans.TtrnProjectisssues;
import com.ibm.ioes.npd.hibernate.beans.TtrnProjectrisks;
import com.ibm.ioes.npd.utilities.PagingSorting;


/**
 * TmAppconfig generated by hbm2java
 */

public class ProjectDetailedStatusReportBean extends ActionForm  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private TtrnProjectassumptions projectassumption; 
	private TtrnProjectrisks projectrisk;
	private TtrnProjectisssues projectissues;
	private TtrnProjecthierarchy projecthierarchy; 
	
	private String projectName;
	private String npdCategory;
	private String productCategory;
	private String airtelPotential;
	private String totalMarketPotential;
	private String capexRequirement;	

	
	private String dateFilter=null;
	private String fromDate=null;
	private String toDate=null;
	PagingSorting pagingSorting=null;
	private String searchProjectPlanName;
	private String searchNpdCategory;
	private String searchProjectName;
	private String searchProjectid;
	private String searchProductCatId;
	private String projectID;
	private String searchByProjectid;
	
	private String stageName;
	private String taskName;
	private String docName;
	private String docType;
	private String projectStatus;
	private String roleName;
	private String delays;
	
	private ArrayList listProjectdetailed;
	
	private int reportID;
	private int checkRptData;
	
	private String docProjectId=null;
	private String docTaskId=null;
	private String docDocName=null;
	
	
	public int getCheckRptData() {
		return checkRptData;
	}

	public void setCheckRptData(int checkRptData) {
		this.checkRptData = checkRptData;
	}

	public int getReportID() {
		return reportID;
	}

	public void setReportID(int reportID) {
		this.reportID = reportID;
	}

	public String getSearchByProjectid() {
		return searchByProjectid;
	}

	public void setSearchByProjectid(String searchByProjectid) {
		this.searchByProjectid = searchByProjectid;
	}

	public String getProjectID() {
		return projectID;
	}

	public void setProjectID(String projectID) {
		this.projectID = projectID;
	}

	public ProjectDetailedStatusReportBean()
	{
		//System.err.println("in constructor");
		pagingSorting=new PagingSorting();
	}



	public String getDateFilter() {
		return dateFilter;
	}



	public void setDateFilter(String dateFilter) {
		this.dateFilter = dateFilter;
	}



	public String getFromDate() {
		return fromDate;
	}



	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}



	public PagingSorting getPagingSorting() {
		return pagingSorting;
	}



	public void setPagingSorting(PagingSorting pagingSorting) {
		this.pagingSorting = pagingSorting;
	}



	public TtrnProjectassumptions getProjectassumption() {
		return projectassumption;
	}



	public void setProjectassumption(TtrnProjectassumptions projectassumption) {
		this.projectassumption = projectassumption;
	}



	public TtrnProjecthierarchy getProjecthierarchy() {
		return projecthierarchy;
	}



	public void setProjecthierarchy(TtrnProjecthierarchy projecthierarchy) {
		this.projecthierarchy = projecthierarchy;
	}



	public TtrnProjectisssues getProjectissues() {
		return projectissues;
	}



	public void setProjectissues(TtrnProjectisssues projectissues) {
		this.projectissues = projectissues;
	}



	public TtrnProjectrisks getProjectrisk() {
		return projectrisk;
	}



	public void setProjectrisk(TtrnProjectrisks projectrisk) {
		this.projectrisk = projectrisk;
	}



	public String getSearchProjectPlanName() {
		return searchProjectPlanName;
	}



	public void setSearchProjectPlanName(String searchProjectPlanName) {
		this.searchProjectPlanName = searchProjectPlanName;
	}

	public String getToDate() {
		return toDate;
	}



	public void setToDate(String toDate) {
		this.toDate = toDate;
	}



	public String getSearchNpdCategory() {
		return searchNpdCategory;
	}



	public void setSearchNpdCategory(String searchNpdCategory) {
		this.searchNpdCategory = searchNpdCategory;
	}



	public String getSearchProjectName() {
		return searchProjectName;
	}



	public void setSearchProjectName(String searchProjectName) {
		this.searchProjectName = searchProjectName;
	}




	public String getAirtelPotential() {
		return airtelPotential;
	}



	public void setAirtelPotential(String airtelPotential) {
		this.airtelPotential = airtelPotential;
	}



	public String getCapexRequirement() {
		return capexRequirement;
	}



	public void setCapexRequirement(String capexRequirement) {
		this.capexRequirement = capexRequirement;
	}



	public String getNpdCategory() {
		return npdCategory;
	}



	public void setNpdCategory(String npdCategory) {
		this.npdCategory = npdCategory;
	}



	public String getProductCategory() {
		return productCategory;
	}



	public void setProductCategory(String productCategory) {
		this.productCategory = productCategory;
	}



	public String getProjectName() {
		return projectName;
	}



	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}



	public String getTotalMarketPotential() {
		return totalMarketPotential;
	}



	public void setTotalMarketPotential(String totalMarketPotential) {
		this.totalMarketPotential = totalMarketPotential;
	}



	public String getSearchProjectid() {
		return searchProjectid;
	}



	public void setSearchProjectid(String searchProjectid) {
		this.searchProjectid = searchProjectid;
	}



	public String getSearchProductCatId() {
		return searchProductCatId;
	}



	public void setSearchProductCatId(String searchProductCatId) {
		this.searchProductCatId = searchProductCatId;
	}

	public String getDelays() {
		return delays;
	}

	public void setDelays(String delays) {
		this.delays = delays;
	}

	public String getDocName() {
		return docName;
	}

	public void setDocName(String docName) {
		this.docName = docName;
	}

	public String getDocType() {
		return docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	public String getProjectStatus() {
		return projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getStageName() {
		return stageName;
	}

	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

	public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public ArrayList getListProjectdetailed() {
		return listProjectdetailed;
	}

	public void setListProjectdetailed(ArrayList listProjectdetailed) {
		this.listProjectdetailed = listProjectdetailed;
	}

	public String getDocDocName() {
		return docDocName;
	}

	public void setDocDocName(String docDocName) {
		this.docDocName = docDocName;
	}

	public String getDocProjectId() {
		return docProjectId;
	}

	public void setDocProjectId(String docProjectId) {
		this.docProjectId = docProjectId;
	}

	public String getDocTaskId() {
		return docTaskId;
	}

	public void setDocTaskId(String docTaskId) {
		this.docTaskId = docTaskId;
	}
	
}
