package com.ibm.ioes.npd.beans;

// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;

import org.apache.struts.action.ActionForm;

import com.ibm.ioes.npd.utilities.PagingSorting;

/**
 * TmAppconfig generated by hbm2java
 */

public class ProjectPlanReportBean extends ActionForm implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int stageid;

	private String stagename;

	private int taskid;

	private String taskname;

	private Date plannedstartdate;

	private Date plannedenddate;

	private Date actualstartdate;

	private Date actualenddate;

	private String stakeholderrole;

	private String stakeholdername;

	private int delayindays;

	private String projectPlanId;

	private String searchProjectPlanName;

	private String searchStageName;

	private String searchTaskName;

	private String searchProjectId;

	private String dateFilter = null;

	private String fromDate = null;

	private String toDate = null;

	private String projectActionId;

	private String fileName;

	private String projectId;

	private String taskId;

	private String stageId;

	private String projectStatusFilter = "-1"; // Default Value is -1 For All
												// Projects

	private String searchprojectid;

	private String searchprojectname;

	private String docid;

	private String rfidocname;

	private int searchProjectStatus;
	
	private int checkFlag;
	
	private int daysInProject;
	
	private String taskStatus;
	
	private String taskDelayValue;
	
	private String monthName;

	// private String pageNumber="1";
	// private String maxPageNumber=null;//getter setter
	// private String sortBy=null;
	// private String sortByOrder=null; //getter setter

	private PagingSorting pagingSorting = null;

	public ProjectPlanReportBean() {
		//System.err.println("in constructor");
		pagingSorting = new PagingSorting();
	}

	public Date getActualenddate() {
		return actualenddate;
	}

	public void setActualenddate(Date actualenddate) {
		this.actualenddate = actualenddate;
	}

	public Date getActualstartdate() {
		return actualstartdate;
	}

	public void setActualstartdate(Date actualstartdate) {
		this.actualstartdate = actualstartdate;
	}

	public int getDelayindays() {
		return delayindays;
	}

	public void setDelayindays(int delayindays) {
		this.delayindays = delayindays;
	}

	public Date getPlannedenddate() {
		return plannedenddate;
	}

	public void setPlannedenddate(Date plannedenddate) {
		this.plannedenddate = plannedenddate;
	}

	public Date getPlannedstartdate() {
		return plannedstartdate;
	}

	public void setPlannedstartdate(Date plannedstartdate) {
		this.plannedstartdate = plannedstartdate;
	}

	public int getStageid() {
		return stageid;
	}

	public void setStageid(int stageid) {
		this.stageid = stageid;
	}

	public String getStagename() {
		return stagename;
	}

	public void setStagename(String stagename) {
		this.stagename = stagename;
	}

	public String getStakeholdername() {
		return stakeholdername;
	}

	public void setStakeholdername(String stakeholdername) {
		this.stakeholdername = stakeholdername;
	}

	public String getStakeholderrole() {
		return stakeholderrole;
	}

	public void setStakeholderrole(String stakeholderrole) {
		this.stakeholderrole = stakeholderrole;
	}

	public int getTaskid() {
		return taskid;
	}

	public void setTaskid(int taskid) {
		this.taskid = taskid;
	}

	public String getTaskname() {
		return taskname;
	}

	public void setTaskname(String taskname) {
		this.taskname = taskname;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public PagingSorting getPagingSorting() {
		return pagingSorting;
	}

	public void setPagingSorting(PagingSorting pagingSorting) {
		this.pagingSorting = pagingSorting;
	}

	public String getSearchProjectPlanName() {
		return searchProjectPlanName;
	}

	public void setSearchProjectPlanName(String searchProjectPlanName) {
		this.searchProjectPlanName = searchProjectPlanName;
	}

	public String getSearchStageName() {
		return searchStageName;
	}

	public void setSearchStageName(String searchStageName) {
		this.searchStageName = searchStageName;
	}

	public String getProjectPlanId() {
		return projectPlanId;
	}

	public void setProjectPlanId(String projectPlanId) {
		this.projectPlanId = projectPlanId;
	}

	public String getSearchTaskName() {
		return searchTaskName;
	}

	public void setSearchTaskName(String searchTaskName) {
		this.searchTaskName = searchTaskName;
	}

	public String getDateFilter() {
		return dateFilter;
	}

	public void setDateFilter(String dateFilter) {
		this.dateFilter = dateFilter;
	}

	public String getFromDate() {
		return fromDate;
	}

	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	public String getToDate() {
		return toDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}

	public String getSearchProjectId() {
		return searchProjectId;
	}

	public void setSearchProjectId(String searchProjectId) {
		this.searchProjectId = searchProjectId;
	}

	public String getProjectActionId() {
		return projectActionId;
	}

	public void setProjectActionId(String projectActionId) {
		this.projectActionId = projectActionId;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getProjectStatusFilter() {
		return projectStatusFilter;
	}

	public void setProjectStatusFilter(String projectStatusFilter) {
		this.projectStatusFilter = projectStatusFilter;
	}

	public String getProjectId() {
		return projectId;
	}

	public void setProjectId(String projectId) {
		if (projectId != null) {
			this.projectId = projectId.trim();
		}
	}

	public String getStageId() {
		return stageId;
	}

	public void setStageId(String stageId) {
		this.stageId = stageId;
	}

	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public String getSearchprojectid() {
		return searchprojectid;
	}

	public void setSearchprojectid(String searchprojectid) {
		if (searchprojectid != null) {
			this.searchprojectid = searchprojectid.trim();
		}
	}

	public String getSearchprojectname() {
		return searchprojectname;
	}

	public void setSearchprojectname(String searchprojectname) {
		this.searchprojectname = searchprojectname;
	}

	public String getDocid() {
		return docid;
	}

	public void setDocid(String docid) {
		this.docid = docid;
	}

	public String getRfidocname() {
		return rfidocname;
	}

	public void setRfidocname(String rfidocname) {
		this.rfidocname = rfidocname;
	}

	public int getSearchProjectStatus() {
		return searchProjectStatus;
	}

	public void setSearchProjectStatus(int searchProjectStatus) {
		this.searchProjectStatus = searchProjectStatus;
	}

	public int getCheckFlag() {
		return checkFlag;
	}

	public void setCheckFlag(int checkFlag) {
		this.checkFlag = checkFlag;
	}

	public int getDaysInProject() {
		return daysInProject;
	}

	public void setDaysInProject(int daysInProject) {
		this.daysInProject = daysInProject;
	}

	public String getTaskStatus() {
		return taskStatus;
	}

	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus;
	}

	public String getTaskDelayValue() {
		return taskDelayValue;
	}

	public void setTaskDelayValue(String taskDelayValue) {
		this.taskDelayValue = taskDelayValue;
	}

	public String getMonthName() {
		return monthName;
	}

	public void setMonthName(String monthName) {
		this.monthName = monthName;
	}

}
