package com.ibm.ioes.npd.beans;

// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;

import org.apache.struts.action.ActionForm;

import com.ibm.ioes.npd.utilities.PagingSorting;

/**
 * TmAppconfig generated by hbm2java
 */

public class QueryBuilderBean extends ActionForm implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String query;
	private String method;

	public String getQuery() {
	    return query;
	}

	public String getMethod() {
	    return method;
	}

	public void setMethod(String method) {
	    this.method = method;
	}

	public void setQuery(String query) {
	    this.query = query;
	}

}
