package com.ibm.ioes.model;

//[215] Raveendra      12-feb-2015    Advance payment refund process 
//[001] Gunjan Singla  24-Oct-2016    CBR-ANG bandwidth correction in iB2B and M6

public class CopyOrderSqlDeclaration {
	
	public static String getSqlServiceDetails(){
		//[001] Start- changes made in query to copy required attributes
		StringBuilder sql=new StringBuilder("SELECT  SERVICE.SERVICEID,SERVICETYPEID, SERVICESTAGE, EFFSTARTDATE, CUSTLOGICALSINO, ")
		.append(" EFFENDDATE, PROVISIONINGPLAN, REMARKS, SERVICESUBSTYPEID, ")
		.append(" PREORDERNO, OLDCUSTLOGICALSINO,SERVICE.ORDERNO, ")
		.append(" CHANGE_TYPE,CREATED_DATE, MODIFIED_DATE ,RFS_DATE,PRODUCTID,SUBPRODUCTID,SUBCHANGETYPEID, IS_DEMO,")
		.append(" BUNDLED,DOWNTIME_CLAUSE,IS_SERVICE_VALIDATED,ACCOUNTID,SERVICE_FLAVOUR,CKT_TYPE ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TPOMASTER TPOMASTER ")
		.append(" ON SERVICE.ORDERNO=TPOMASTER.ORDERNO ")
		.append(" INNER JOIN IOE.TPOSERVICEMASTER_EXTENDED SERVICE_EXT") 
		.append(" ON SERVICE_EXT.SERVICEID=SERVICE.SERVICEID")	
		.append(" WHERE SERVICE.SERVICEID IN(@csvServiceIds) ");
		//[001] End
		
		return sql.toString();
	}
	public static String getSqlServiceLevelAttributeDetails(){
		StringBuilder sql=new StringBuilder("SELECT  LABELATTID, LABELATTVALUE,SERVICEDETAILID FROM IOE.TPRODUCTATTVALUE WHERE SERVICEDETAILID IN(@csvServiceIds)");
		
		return sql.toString();
	}
	//[001] Start- query changed for Drop and Carry
	public static String getSqlLineDetails(){
		StringBuilder sql=new StringBuilder("SELECT SERVICE.SERVICEID, LINE.SERVICEDETAILID,LINE.SERVICEPRODUCTID,LINE.PARENT_SERVICEPRODUCTID,   ")
		.append("LINE.LOGICALCIRCUITID,LINE.INFRAORDERNO,LINE.METASOLVCIRCUITID,LINE.CONFIG_ID,LINE.ISDUMMY  ") 
		.append("FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS   ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=0   ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS LINE   ")
		.append("ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE.SERVICEPRODUCTID  ") 
		.append("INNER JOIN IOE.TSERVICETYPEDETAIL LINE_TYPE ")
		.append("ON LINE.SERVICEDETAILID=LINE_TYPE.SERVICEDETAILID AND LINE_TYPE.ISACTIVE=1 ")
		.append("WHERE  SERVICE.SERVICEID IN(@csvServiceIds)   ")
		.append("UNION ALL    ")
		.append("SELECT SERVICE.SERVICEID, LINE_HIS.SERVICEDETAILID,LINE_HIS.SERVICEPRODUCTID,LINE_HIS.PARENT_SERVICEPRODUCTID,  ") 
		.append("LINE_HIS.LOGICALCIRCUITID,LINE_HIS.INFRAORDERNO,LINE_HIS.METASOLVCIRCUITID,LINE_HIS.CONFIG_ID,FRONT_LINE.ISDUMMY  ") 
		.append("FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS   ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=1   ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS_HISTORY LINE_HIS   ")
		.append("ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE_HIS.SERVICEPRODUCTID AND LINE_HIS.MAIN_SERVICEID=SERVICE.SERVICEID  ") 
		.append("INNER JOIN IOE.TPOSERVICEDETAILS FRONT_LINE   ")
		.append("ON FRONT_LINE.SERVICEPRODUCTID=LINE_HIS.SERVICEPRODUCTID  ")
		.append("INNER JOIN IOE.TSERVICETYPEDETAIL LINE_TYPE ") 
        .append("ON FRONT_LINE.SERVICEDETAILID=LINE_TYPE.SERVICEDETAILID AND LINE_TYPE.ISACTIVE=1 ")
		.append("WHERE SERVICE.SERVICEID IN(@csvServiceIds)  ");
		return sql.toString();
	}
	public static String getSqlLineLevelAttributeDetails(){
		StringBuilder sql=new StringBuilder("SELECT ATTVALUEID,ATTVALUE.ATTMASTERID,ATTVALUE,ATTVALUE_NEW,SERVICEPRODUCTID,ATTDESCRIPTION ")
		.append(" FROM IOE.TPRODUCTLINEATTVALUE_HISTORY ATTVALUE ")
		.append(" INNER JOIN IOE.TPRODUCTLINEATTMASTER ATTMASTER ")
		.append(" ON ATTMASTER.ATTMASTERID=ATTVALUE.ATTMASTERID ")
		.append(" WHERE MAIN_SERVICE_ID IN(@csvServiceIds)");
		return sql.toString();
	}
	public static String getSqlLineCinfigAttributeDetails(){
		StringBuilder sql=new StringBuilder("SELECT LINE_CONFIG.SERVICEPRODUCTID,LINE_CONFIG.ATTRIBUTE_ID,LINE_CONFIG.ATTRIBUTE_VALUE,LINE_CONFIG.MILESTONE_STATUS  ")
		.append("FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID   ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS LINE  ")
		.append("ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE.SERVICEPRODUCTID   ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS_CONFIGATT_VALUES LINE_CONFIG  ")
		.append("ON LINE_CONFIG.SERVICEPRODUCTID=LINE.SERVICEPRODUCTID  ")
		.append("WHERE SERVICE.SERVICEID IN(@csvServiceIds)  ");
		return sql.toString();
	}
	public static String getSqlBillingInfoDetails(){
		StringBuilder sql=new StringBuilder("SELECT LINE.SERVICEPRODUCTID,PODETAILID, BILLING_INFO.ACCOUNTID,CREDITPERIOD,BILLINGMODE,NOTICEPERIOD,  ")
		.append("BILLINGFORMAT,TAXATION,BILLINGLEVEL,COMMITMENTPERIOD,PENALTYCLAUSE,  ")
		.append("BILLINGTYPE,BILLING_INFO.BCPID,BILLING_LEVEL_NO,BILLING_INFO.STDREASION_ID ,LICENCECOID ,BILLING_INFO.ENTITYID, IS_NFA,ISUSAGE,WARRANTYCLAUSE,SERVICE_BCPID,IS_OSP,OSP_REG_NO,OSP_REG_DATE  ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=0  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS LINE  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE.SERVICEPRODUCTID   ")
		.append("INNER JOIN IOE.TBILLING_INFO BILLING_INFO  ")
		.append("ON BILLING_INFO.SERVICEPRODUCTID=LINE.SERVICEPRODUCTID  ")
		.append("WHERE SERVICE.SERVICEID IN(@csvServiceIds)  ")
		.append("UNION ALL  ")
		.append("SELECT LINE_HIS.SERVICEPRODUCTID,PODETAILID,BILLING_INFO_HIS.ACCOUNTID,CREDITPERIOD,BILLINGMODE,NOTICEPERIOD,  ")
		.append("BILLINGFORMAT,TAXATION,BILLINGLEVEL,COMMITMENTPERIOD,PENALTYCLAUSE,  ")
		.append("BILLINGTYPE,BILLING_INFO_HIS.BCPID,BILLING_LEVEL_NO,BILLING_INFO_HIS.STDREASION_ID ,LICENCECOID ,BILLING_INFO_HIS.ENTITYID, IS_NFA,ISUSAGE,WARRANTYCLAUSE,SERVICE_BCPID,IS_OSP,OSP_REG_NO,OSP_REG_DATE  ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=1  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS_HISTORY LINE_HIS  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE_HIS.SERVICEPRODUCTID AND LINE_HIS.MAIN_SERVICEID=SERVICE.SERVICEID  ")
		.append("INNER JOIN IOE.TBILLING_INFO_HISTORY BILLING_INFO_HIS  ")
		.append("ON BILLING_INFO_HIS.SERVICEPRODUCTID=LINE_HIS.SERVICEPRODUCTID AND BILLING_INFO_HIS.MAIN_SERVICE_ID=SERVICE.SERVICEID  ")
		.append("WHERE  SERVICE.SERVICEID IN(@csvServiceIds)  ");
		return sql.toString();
	}
	public static String getSqlLocationInfoDetails(){
		StringBuilder sql=new StringBuilder("SELECT LINE.SERVICEPRODUCTID, PRIMARYLOCATIONTYPE,PRIMARYLOCATIONID,SECONDARYLOCATIONTYPE, ")
		.append("SECONDARYLOCATIONID,LOCATION_INFO.ACCOUNTID,TO_ADDRESS,FROM_ADDRESS ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=0 ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS LINE ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE.SERVICEPRODUCTID  ")
		.append("INNER JOIN IOE.TLOCATION_INFO LOCATION_INFO ")
		.append("ON LOCATION_INFO.SERVICEPRODUCTID=LINE.SERVICEPRODUCTID ")
		.append("WHERE SERVICE.SERVICEID IN(@csvServiceIds) ")
		.append("UNION ALL ")
		.append("SELECT LINE_HIS.SERVICEPRODUCTID,PRIMARYLOCATIONTYPE,PRIMARYLOCATIONID,SECONDARYLOCATIONTYPE, ")
		.append("SECONDARYLOCATIONID,LOCATION_INFO_HIS.ACCOUNTID,TO_ADDRESS,FROM_ADDRESS ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=1 ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS_HISTORY LINE_HIS ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE_HIS.SERVICEPRODUCTID AND LINE_HIS.MAIN_SERVICEID=SERVICE.SERVICEID ")
		.append("INNER JOIN IOE.TLOCATION_INFO_HISTORY LOCATION_INFO_HIS ")
		.append("ON LOCATION_INFO_HIS.SERVICEPRODUCTID=LINE_HIS.SERVICEPRODUCTID AND LOCATION_INFO_HIS.MAIN_SERVICE_ID=SERVICE.SERVICEID ")
		.append("WHERE  SERVICE.SERVICEID IN(@csvServiceIds) ");
		return sql.toString();
	}
	public static String getSqlHardwareInfoDetails(){
		StringBuilder sql=new StringBuilder("SELECT LINE.SERVICEPRODUCTID,STOREID,HARDWARETYPE,FORMAVAILABLE,SALETYPE,SALENATURE,DISPATCHADDCODE,  ")
		.append("HARDWARE_INFO.ACCOUNTID,STARTDATELOGIC,ENDDATELOGIC,  ")
		.append("WARRENTYMONTHS,PRINCIPAL_AMOUNT,INTEREST_RATE ,  ")
		.append("START_MONTHS,END_DAYS,END_MONTH,EXT_DAYS,EXT_MONTHS,START_DAYS,DISPATCH_CONTACTNAME  ")
		.append("FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=0  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS LINE  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE.SERVICEPRODUCTID   ")
		.append("INNER JOIN IOE.THARDWARE_INFO HARDWARE_INFO  ")
		.append("ON HARDWARE_INFO.SERVICEPRODUCTID=LINE.SERVICEPRODUCTID  ")
		.append("WHERE SERVICE.SERVICEID IN(@csvServiceIds)  ")
		.append("UNION ALL  ")
		.append("SELECT LINE_HIS.SERVICEPRODUCTID,STOREID,HARDWARETYPE,FORMAVAILABLE,SALETYPE,SALENATURE,DISPATCHADDCODE,  ")
		.append("HARDWARE_INFO_HIS.ACCOUNTID,STARTDATELOGIC,ENDDATELOGIC,  ")
		.append("WARRENTYMONTHS,PRINCIPAL_AMOUNT,INTEREST_RATE,  ")
		.append("START_MONTHS,END_DAYS,END_MONTH,EXT_DAYS,EXT_MONTHS,START_DAYS,DISPATCH_CONTACTNAME  ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=1  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS_HISTORY LINE_HIS  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE_HIS.SERVICEPRODUCTID AND LINE_HIS.MAIN_SERVICEID=SERVICE.SERVICEID  ")
		.append("INNER JOIN IOE.THARDWARE_INFO_HISTORY HARDWARE_INFO_HIS  ")
		.append("ON HARDWARE_INFO_HIS.SERVICEPRODUCTID=LINE_HIS.SERVICEPRODUCTID AND HARDWARE_INFO_HIS.MAIN_SERVICE_ID=SERVICE.SERVICEID  ")
		.append("WHERE  SERVICE.SERVICEID IN(@csvServiceIds)  ");
		return sql.toString();
	}
	public static String getSqlChargeInfoDetails(){
		StringBuilder sql=new StringBuilder("SELECT LINE.SERVICEPRODUCTID, CHARGES_INFO.ACCOUNTID,CHARGESTYPE,CHARGENAME,CHARGEPERIOD,CHARGEAMOUNT,CHARGEFREQUENCY,  ")
		.append("CHARGEFREQUENCYAMT,STARTDATELOGIC,ENDDATELOGIC,CHARGEINFOID,CHARGES_INFO.PODETAILNO,  ")
		.append("START_DATE_DAYS,START_DATE_MONTH,END_DATE_DAYS,END_DATE_MONTH,ANNOTATION,EXCLUDE,  ")
		.append("CHARGES_INFO.REMARKS,PAYMENTTERM1,PAYMENTTERM2,PAYMENTTERM3,PAYMENTTERM4,TAXRATE,LINEITEMID,SUBLINEITEMID ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=0  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS LINE  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE.SERVICEPRODUCTID   ")
		.append("INNER JOIN IOE.TCHARGES_INFO CHARGES_INFO  ")
		.append("ON CHARGES_INFO.SERVICEPRODUCTID=LINE.SERVICEPRODUCTID AND CHARGES_INFO.CREATEDIN_SERVICEID=SERVICE.SERVICEID  ")
		.append("WHERE SERVICE.SERVICEID IN(@csvServiceIds)  ")
		.append("UNION ALL  ")
		.append("SELECT LINE_HIS.SERVICEPRODUCTID,ACCOUNTID,CHARGESTYPE,CHARGENAME,CHARGEPERIOD,CHARGEAMOUNT,CHARGEFREQUENCY,  ")
		.append("CHARGEFREQUENCYAMT,STARTDATELOGIC,ENDDATELOGIC,CHARGEINFOID,CHARGES_INFO_HIS.PODETAILNO,  ")
		.append("START_DATE_DAYS,START_DATE_MONTH,END_DATE_DAYS,END_DATE_MONTH,ANNOTATION,EXCLUDE,  ")
		.append("CHARGES_INFO_HIS.REMARKS,PAYMENTTERM1,PAYMENTTERM2,PAYMENTTERM3,PAYMENTTERM4,TAXRATE,LINEITEMID,SUBLINEITEMID ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=1  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS_HISTORY LINE_HIS  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE_HIS.SERVICEPRODUCTID AND LINE_HIS.MAIN_SERVICEID=SERVICE.SERVICEID  ")
		.append("INNER JOIN IOE.TCHARGES_INFO_HISTORY CHARGES_INFO_HIS  ")
		.append("ON CHARGES_INFO_HIS.SERVICEPRODUCTID=LINE_HIS.SERVICEPRODUCTID AND CHARGES_INFO_HIS.MAIN_SERVICE_ID=SERVICE.SERVICEID  ")
		.append("WHERE  SERVICE.SERVICEID IN(@csvServiceIds)  ");
		return sql.toString();
	}
	public static String getSqlComponentInfoDetails(){
		StringBuilder sql=new StringBuilder("SELECT ACCOUNTID,LINE.SERVICEPRODUCTID,COMPONENT_ID,PACKAGE_ID,")
		.append("COMPONENT_STATUS,CREATEDIN_SERVICEID,DISCONNECTED_IN_SERVICEID,COMPONENT_START_LOGIC, COMPONENT_END_LOGIC,START_DAYS,START_MONTHS,END_DAYS,END_MONTHS  ")
		.append("FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=0  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS LINE  ")
		.append("ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE.SERVICEPRODUCTID   ")
		.append("INNER JOIN IOE.TCOMPONENT_INFO COMPONENT_INFO  ")
		.append("ON COMPONENT_INFO.SERVICEPRODUCTID=LINE.SERVICEPRODUCTID AND COMPONENT_INFO.CREATEDIN_SERVICEID=SERVICE.SERVICEID  ")
		.append("WHERE SERVICE.SERVICEID IN(@csvServiceIds)  ")
		.append("UNION ALL  ")
		.append("SELECT ACCOUNTID,LINE_HIS.SERVICEPRODUCTID, COMPONENT_ID,PACKAGE_ID,COMPONENT_STATUS,CREATEDIN_SERVICEID," )
		.append("DISCONNECTED_IN_SERVICEID,COMPONENT_START_LOGIC, COMPONENT_END_LOGIC,START_DAYS,START_MONTHS,END_DAYS,END_MONTHS  ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=1  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS_HISTORY LINE_HIS  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE_HIS.SERVICEPRODUCTID AND LINE_HIS.MAIN_SERVICEID=SERVICE.SERVICEID  ")
		.append("INNER JOIN IOE.TCOMPONENT_INFO_HISTORY COMPONENT_INFO_HIS  ")
		.append("ON COMPONENT_INFO_HIS.SERVICEPRODUCTID=LINE_HIS.SERVICEPRODUCTID AND COMPONENT_INFO_HIS.MAIN_SERVICE_ID=SERVICE.SERVICEID  ")
		.append("WHERE  SERVICE.SERVICEID IN(@csvServiceIds)  ");
		return sql.toString();
	}
	public static String getSqlAdvancePaymentDetails(){
		//[215] added ARCRECHQAMT, ARCRECHQNO, ARCBANKACNO, ARCREBANKACNO, ARCIFSCCODE, ARCREIFSCCODE, OTCRECHQAMT, OTCRECHQNO, OTCBANKACNO, OTCREBANKACNO, OTCIFSCCODE, OTCREIFSCCODE
		
		StringBuilder sql=new StringBuilder("SELECT ADVANCEPAYMENT.SPID,ARCEXEMPTED, ARCEXPREASON, ARCCHQNO, ARCCHQDATE, ARCBANKNAME,   ")
		.append("ARCCHQAMT, ARCAMTAJD, OTCEXEMPTED, OTCEXPREASON, OTCCHQNO, OTCCHQDATE, OTCBANKNAME,   ")
		.append("OTCCHQAMT,OTCAMTAJD, ARCRECHQAMT, ARCRECHQNO, ARCBANKACNO, ARCREBANKACNO, ARCIFSCCODE, ARCREIFSCCODE, OTCRECHQAMT, OTCRECHQNO, OTCBANKACNO, OTCREBANKACNO, OTCIFSCCODE, OTCREIFSCCODE")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID   ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS LINE  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE.SERVICEPRODUCTID   ")
		.append("INNER JOIN IOE.TADVANCEPAYMENT ADVANCEPAYMENT  ")
		.append("ON ADVANCEPAYMENT.SPID=LINE.SERVICEPRODUCTID AND ADVANCEPAYMENT.SERVICENO=SERVICE.SERVICEID  ")
		.append("WHERE SERVICE.SERVICEID IN(@csvServiceIds)  ");
		return sql.toString();
	}
	public static String getSqlLineChargeValueSCM(){
		StringBuilder sql=new StringBuilder("SELECT ITEM_CODE, QUANTITY, CHARGEVALUE,PRODUCTLINECHARGEVALUE_SCM.SERVICEPRODUCTID,PRODUCTLINECHARGEVALUE_SCM.CREATEDDATE, PRODUCTLINECHARGEVALUE_SCM.CREATEDBY,   ")
		.append("PRODUCTLINECHARGEVALUE_SCM.MODIFIEDDATE, PRODUCTLINECHARGEVALUE_SCM.MODIFIEDBY, DEL_ID, SUBINV_ID, AOP1_ID, AOP2_ID,IS_ACTIVE, AOP_YEAR,PO_NUMBER, PO_DATE,PO_AMOUNT  ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=0  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS LINE  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE.SERVICEPRODUCTID  ") 
		.append("INNER JOIN IOE.TPRODUCTLINECHARGEVALUE_SCM PRODUCTLINECHARGEVALUE_SCM  ")
		.append("ON PRODUCTLINECHARGEVALUE_SCM.SERVICEPRODUCTID=LINE.SERVICEPRODUCTID   ")
		.append("WHERE SERVICE.SERVICEID IN(@csvServiceIds) ")
		.append("UNION ALL  ")
		.append("SELECT ITEM_CODE, QUANTITY, CHARGEVALUE,PRODUCTLINECHARGEVALUE_SCM_HIS.SERVICEPRODUCTID,PRODUCTLINECHARGEVALUE_SCM_HIS.CREATEDDATE,PRODUCTLINECHARGEVALUE_SCM_HIS.CREATEDBY,   ")
		.append("PRODUCTLINECHARGEVALUE_SCM_HIS.MODIFIEDDATE, PRODUCTLINECHARGEVALUE_SCM_HIS.MODIFIEDBY, DEL_ID, SUBINV_ID, AOP1_ID, AOP2_ID,IS_ACTIVE, AOP_YEAR,PO_NUMBER, PO_DATE,PO_AMOUNT  ")
		.append(" FROM IOE.TPOSERVICEMASTER SERVICE INNER JOIN IOE.TDISCONNECTION_HISTORY DISCONN_HIS  ")
		.append("ON DISCONN_HIS.MAIN_SERVICEID=SERVICE.SERVICEID AND SERVICE.IS_IN_HISTORY=1  ")
		.append("INNER JOIN IOE.TPOSERVICEDETAILS_HISTORY LINE_HIS  ")
		.append(" ON DISCONN_HIS.SERVICE_PRODUCT_ID=LINE_HIS.SERVICEPRODUCTID AND LINE_HIS.MAIN_SERVICEID=SERVICE.SERVICEID  ")
		.append("INNER JOIN IOE.TPRODUCTLINECHARGEVALUE_SCM_HISTORY PRODUCTLINECHARGEVALUE_SCM_HIS  ")
		.append("ON PRODUCTLINECHARGEVALUE_SCM_HIS.SERVICEPRODUCTID=LINE_HIS.SERVICEPRODUCTID AND PRODUCTLINECHARGEVALUE_SCM_HIS.MAIN_SERVICE_ID=SERVICE.SERVICEID  ")
		.append("WHERE  SERVICE.SERVICEID IN(@csvServiceIds) ");
		return sql.toString();
	}
	public static String getSqlCurrentOrderPODetails(){
		StringBuilder sql=new StringBuilder("SELECT PODETAILNUMBER,LEGALENTITY FROM ioe.TPODETAILS WHERE PONUMBER=?");
		return sql.toString();
	}
	public static String getSqlThirdPartyServiceDetailId(){
		StringBuilder sql=new StringBuilder("SELECT KEYVALUE AS THIRD_PARTY_SERVICE_DETAILID FROM IOE.TM_APPCONFIG WHERE KEYNAME='THIRD_PARTY_LINE_ITEM_NO'");
		return sql.toString();
	}
	public static String getSqlOrderLevelData(){
		StringBuilder sql=new StringBuilder("SELECT ORDER_TYPE,CHANGETYPEID,ACCOUNTID,(SELECT BCP_ID FROM ioe.TBCP_ADDRESS_MSTR WHERE ACCOUNTID=A.ACCOUNTID fetch first row only)")
		.append(" as BCP_ID, (SELECT DISPATCH_ADDRESS_CODE as DISPATCH_ADDRESS_CODE FROM IOE.TDISPATCH_ADDRESS_MSTR where ACCOUNTID = A.ACCOUNTID fetch first row only) as DISPATCH_ADDRESS_CODE,")
		.append(" (SELECT count(1) FROM IOE.TPOWORKFLOWTASK WHERE ORDERNO = ?) as WORKFLOW_COUNT FROM ioe.TPOMASTER A WHERE ORDERNO= ?");
		return sql.toString();
	}
	public static String insertSqlServiceData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TPOSERVICEMASTER(SERVICEID,SERVICETYPEID,SERVICESTAGE,EFFSTARTDATE,")
		.append("CUSTLOGICALSINO,EFFENDDATE,PROVISIONINGPLAN,REMARKS,")
		.append("SERVICESUBSTYPEID,PREORDERNO,OLDCUSTLOGICALSINO,")
		.append("CHANGE_TYPE,LOGICAL_SI_NO,CUSTOMER_LOGICAL_SI_NO,CREATED_DATE,MODIFIED_DATE,RFS_DATE,PRODUCTID,")
		.append("SUBPRODUCTID,SUBCHANGETYPEID,IS_DEMO,BUNDLED,DOWNTIME_CLAUSE,IS_SERVICE_VALIDATED,ORDERNO,INITIATED_TO,CREATEDBY,MODIFIEDBY) ")
		.append("values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"); 
		return sql.toString();
	}
	//[001] Start
	/*public static String insertSqlServiceExtData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TPOSERVICEMASTER_EXTENDED(SERVICEID, SERVICE_FLAVOUR, CKT_TYPE) ")
		.append("values(?,?,?)"); 
		return sql.toString();
	}*/
	public static String updateSqlServiceExtData(){
		StringBuilder sql=new StringBuilder("UPDATE ioe.TPOSERVICEMASTER_EXTENDED SET SERVICE_FLAVOUR=? ,CKT_TYPE=? WHERE SERVICEID=?"); 
		return sql.toString();
	}
	
	//[001] End
	public static String insertSqlServiceLevelAttributeData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TPRODUCTATTVALUE( LABELATTID, LABELATTVALUE, SERVICEDETAILID,CREATEDDATE,CREATEDBY) values(?,?,?,?,?)");		
		return sql.toString();
	}
	public static String insertSqlLineItemData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TPOSERVICEDETAILS(SERVICEPRODUCTID,SERVICEID,SERVICEDETAILID,PARENT_SERVICEPRODUCTID,")
		.append("ISDISCONNECTED,ISSUSPENDED,ISDISCONNECTEDINFX,ISDISCONNECTEDINM6,ISSUSPENDEDINFX,ISSUSPENDEDINM6," )
		.append("BILLING_TRIGGER_STATUS,LOGICALCIRCUITID, INFRAORDERNO, METASOLVCIRCUITID,CONFIG_ID,ISDUMMY,CREATEDDATE,MODIFIEDDATE,CREATEDBY,MODIFIEDBY)")
		.append(" values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
		return sql.toString();
	}
	public static String insertSqlServiceSummarryData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TPRODUCTLINEATTVALUE(ATTMASTERID,ATTVALUE,SERVICEPRODUCTID,CREATEDBY) values(?,?,?,?)");
		return sql.toString();
	}
	public static String insertSqlServiceSummarryHisData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TPRODUCTLINEATTVALUE_HISTORY(ATTVALUEID, ATTMASTERID,ATTVALUE, ATTVALUE_NEW,SERVICEPRODUCTID,ORDERNO,ORDERTYPE,MAIN_SERVICE_ID,MODIFIEDBY) values(?,?,?,?,?,?,?,?,?)");
		return sql.toString();
	}
	public static String insertSqlBillingInfoData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TBILLING_INFO(ACCOUNTID,CREDITPERIOD,BILLINGMODE,NOTICEPERIOD,")
		.append("BILLINGFORMAT,TAXATION,BILLINGLEVEL,COMMITMENTPERIOD,PENALTYCLAUSE,SERVICEPRODUCTID,")
		.append("BILLINGTYPE,BCPID,SERVICE_BCPID,ISDISCONNECTED,ISSUSPENDED,ISDISCONNECTEDINFX,")
		.append("ISDISCONNECTEDINM6,ISSUSPENDEDINFX,ISSUSPENDEDINM6,BILLING_LEVEL_NO,STDREASION_ID,")
		.append("IS_NFA,ISUSAGE,WARRANTYCLAUSE,PODETAILID,LICENCECOID,ENTITYID,CREATEDBY,IS_OSP,OSP_REG_NO,OSP_REG_DATE)")
		.append(" values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
		return sql.toString();
	}
	public static String insertSqlLocationInfoData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TLOCATION_INFO(PRIMARYLOCATIONTYPE,PRIMARYLOCATIONID,SECONDARYLOCATIONTYPE,")
		.append("SECONDARYLOCATIONID,ACCOUNTID,SERVICEPRODUCTID,ISDISCONNECTED,ISSUSPENDED,")
		.append("ISDISCONNECTEDINFX,ISDISCONNECTEDINM6,ISSUSPENDEDINFX,ISSUSPENDEDINM6,TO_ADDRESS,FROM_ADDRESS,CREATEDBY,MODIFIEDBY)")
		.append(" values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")	;
		return sql.toString();
	}
	public static String insertSqlHardwareInfoData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.THARDWARE_INFO(STOREID,HARDWARETYPE,FORMAVAILABLE,SALETYPE,")
		.append("SALENATURE,DISPATCHADDCODE,ACCOUNTID,SERVICEPRODUCTID,STARTDATELOGIC,ENDDATELOGIC,")
		.append("WARRENTYMONTHS,ISDISCONNECTED,ISSUSPENDED,ISDISCONNECTEDINFX,")	
		.append("ISDISCONNECTEDINM6,ISSUSPENDEDINFX,ISSUSPENDEDINM6,PRINCIPAL_AMOUNT,INTEREST_RATE,")
		.append( "START_MONTHS,END_DAYS,END_MONTH,EXT_DAYS,EXT_MONTHS,START_DAYS,DISPATCH_CONTACTNAME,CREATEDBY)")
		.append( " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
		return sql.toString();
	}
	public static String insertSqlServiceDetailsConfigData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TPOSERVICEDETAILS_CONFIGATT_VALUES(SERVICEPRODUCTID,ATTRIBUTE_ID,ATTRIBUTE_VALUE) values(?,?,?)");
		return sql.toString();
	}
	public static String insertSqlComponentInfoData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TCOMPONENT_INFO(ACCOUNTID,SERVICEPRODUCTID,COMPONENT_ID,ISDISCONNECTED,CREATEDDATE,")
		.append("PACKAGE_ID, COMPONENT_STATUS,  CREATEDIN_SERVICEID, DISCONNECTED_IN_SERVICEID,") 
		.append( "COMPONENT_START_LOGIC, COMPONENT_END_LOGIC,START_DAYS,START_MONTHS,END_DAYS,END_MONTHS)")
		.append( " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"	);
		return sql.toString();
	}
	public static String insertSqlAdvancePaymentData(){
		
		//Start [215] added new field given below
		//ARCRECHQAMT, ARCRECHQNO, ARCBANKACNO, ARCREBANKACNO, ARCIFSCCODE, ARCREIFSCCODE, OTCRECHQAMT, OTCRECHQNO, OTCBANKACNO, OTCREBANKACNO, OTCIFSCCODE, OTCREIFSCCODE
	
		StringBuilder sql=new StringBuilder("INSERT INTO  IOE.TADVANCEPAYMENT (ARCEXEMPTED, ARCEXPREASON, ARCCHQNO, ARCCHQDATE, ARCBANKNAME,")
		.append("ARCCHQAMT, ARCAMTAJD, OTCEXEMPTED, OTCEXPREASON, OTCCHQNO, OTCCHQDATE, OTCBANKNAME, OTCCHQAMT,") 
		.append("OTCAMTAJD, CREATEDBY, CREATEDDATE,ORDERNO, LSINO, SERVICENO, SPID ,ARCRECHQAMT, ARCRECHQNO, ARCBANKACNO, ARCREBANKACNO, ARCIFSCCODE, ARCREIFSCCODE, OTCRECHQAMT, OTCRECHQNO, OTCBANKACNO, OTCREBANKACNO, OTCIFSCCODE, OTCREIFSCCODE)")
		.append(" values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
		return sql.toString();
	}
	public static String insertSqlChargesInfoData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TCHARGES_INFO(SERVICEPRODUCTID,ACCOUNTID,CHARGESTYPE,CHARGENAME,CHARGEPERIOD,")
		.append("CHARGEAMOUNT,CHARGEFREQUENCY,CHARGEFREQUENCYAMT,STARTDATELOGIC,ENDDATELOGIC,")
		.append("ISDISCONNECTEDINFX,ISDISCONNECTEDINM6,ISSUSPENDEDINFX,ISSUSPENDEDINM6,ISDISCONNECTED,")
		.append("ISSUSPENDED,START_DATE_DAYS,START_DATE_MONTH,END_DATE_DAYS,")
		.append("END_DATE_MONTH,ANNOTATION,EXCLUDE,CREATEDIN_SERVICEID,PODETAILNO,REMARKS,PAYMENTTERM1,PAYMENTTERM2,")
		.append("PAYMENTTERM3,PAYMENTTERM4,TAXRATE,LINEITEMID,SUBLINEITEMID,CREATEDBY,CHARGENAME_ID)")
		.append(" values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
		return sql.toString();
	}
	public static String insertSqlSCMInfoData(){
		StringBuilder sql=new StringBuilder("INSERT INTO IOE.TPRODUCTLINECHARGEVALUE_SCM (ITEM_CODE, QUANTITY, CHARGEVALUE, SERVICEPRODUCTID,")
		.append("CREATEDDATE, CREATEDBY, MODIFIEDDATE, MODIFIEDBY, DEL_ID, SUBINV_ID, AOP1_ID, AOP2_ID,IS_ACTIVE,")
		.append("AOP_YEAR, PO_NUMBER, PO_DATE, PO_AMOUNT)")
		.append(" values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
		return sql.toString();
	}
	
	public static String getServiceWithHardwareLinecount(){
		StringBuilder sql=new StringBuilder("SELECT SERVICEID, count(1) as NoOfHardwareLine FROM ioe.TPOSERVICEDETAILS TPOSERVICEDETAILS ")
		.append("INNER JOIN ioe.TSERVICETYPEDETAIL TSERVICETYPEDETAIL on TSERVICETYPEDETAIL.SERVICEDETAILID=TPOSERVICEDETAILS.SERVICEDETAILID ")
		.append(" WHERE HARDWAREINFO=1 and SERVICEID in (@csvServiceIds) group by SERVICEID"); 
		
		return sql.toString();
	}
	
	public static String getServiceList(){
		StringBuilder sql=new StringBuilder("SELECT SERVICEID FROM IOE.TPOSERVICEMASTER WHERE ORDERNO = ?");
		return sql.toString();
	}
	
	public static String getNextOrderNo(){
		StringBuilder sql=new StringBuilder(" SELECT  NEXTVAL FOR IOE.SEQ_ORDER_NO AS NEXT_ORDER_NO  FROM SYSIBM.SYSDUMMY1 ");
		return sql.toString();
	}
	
	public static String getNotAvailableZoneCount(){
		StringBuilder sql=new StringBuilder("SELECT COUNT(1) as NA_REGION_ZONE_ORDER FROM ioe.TPOMASTER TPOM ")
		.append("INNER JOIN IOE.TREGION TREGION ON TPOM.REGIONID=TREGION.REGIONID ")
		.append("INNER JOIN IOE.TZONE TZONE ON TPOM.ZONEID=TZONE.ZONEID  WHERE TPOM.ORDERNO=? ")
		.append("AND (TREGION.REGIONID=1 OR TZONE.ZONEID in(4, 5, 6, 7, 11, 1)) ");
		return sql.toString();
	}
	
	public static String getMigratedServiceCount(){
		StringBuilder sql=new StringBuilder("SELECT count(*) AS IS_MIGRATED_NEW_PROD FROM ioe.TPOSERVICEMASTER TPOSERVICEMASTER ")
		.append("inner join ioe.TPOMASTER TPOMASTER on TPOSERVICEMASTER.ORDERNO=TPOMASTER.ORDERNO ")
		.append("and SERVICETYPEID in(420,421,422,423,424) and TPOMASTER.ORDERNO=? ");
		return sql.toString();
	}
	
	public static String getOldPoAndNewPoMapping(){
		StringBuilder sql=new StringBuilder("SELECT OLD_PODETAILNUMBER as OldPoDetailNo, PODETAILNUMBER as NewPoDetailNo  FROM IOE.TPODETAILS where  PONUMBER = ? with ur ");
		return sql.toString();
	}
	
	public static String getOrderType(){
		StringBuilder sql=new StringBuilder("SELECT ORDERTYPE FROM IOE.TPOMASTER WHERE ORDERNO = ? ");
		return sql.toString();
	}
}
