package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.sql.Array;
import java.sql.Blob;
import java.util.ArrayList;
import java.util.Date;

import org.apache.struts.upload.FormFile;

import com.ibm.ioes.npd.utilities.PagingSorting;


/**
 * TmAppconfig generated by hbm2java
 */

public class PlrUploadingDto  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int stageid ;
	private String stagename;
	private int taskid;
	private String taskname;
	private Date plannedstartdate;
	private Date plannedenddate;
	private Date actualstartdate;
	private Date actualenddate;
	private String stakeholderrole;
	private String stakeholdername;
	private int delayindays;
	
	private String projectPlanId;

	private String dateFilter=null;
	private String fromDate=null;
	private String toDate=null;
	private Blob refdoc;
	private String docName;
	private int projectActionId;
	private int projectStatusFilter;
	
	//private String sortBy=null;
	//private String sortByOrder=null;//getter and setter
	//PagingSorting paging=null;//setter and getter	
	
	PagingSorting pagingSorting=null;
	
	
	private String searchProjectPlanName;
	private String searchStageName;
	private String searchTaskName;
	private String searchProjectId;
	private String searchLaunchPriority;
	private String sortBy=null;
	private String sortByOrder=null;  /*values : "increment" ,"decrement"  */
	private TtrnProject projectDetails;
	private String stakeholderidlist;
	private int plannedduration;
	private FormFile attachment;
	
	private String refDocName;
	private String createdBy;
	private Date createdDate;
	private String version;
	private Blob attachedFile;
	private String stakeholderid;
	private int isupload;
	private int userId;
	private int roleId;
	private ArrayList<TmEmployee> tmployeelst;
	private String[] employeeId;
	private String dayforplr;
	private String roleid;
	private String rolename;
	private TmEmployee tmployee;
	private String ismapped;
	private String monthid;
	private ArrayList monthlst;
	private String monthlabel;
	private String monthvalue;
	private String searchPlrId;
	private String employeelabel;
	private String employeevalue;

	
	public String getIsmapped() {
		return ismapped;
	}
	public void setIsmapped(String ismapped) {
		this.ismapped = ismapped;
	}
	public TmEmployee getTmployee() {
		return tmployee;
	}
	public void setTmployee(TmEmployee tmployee) {
		this.tmployee = tmployee;
	}
	public String getRoleid() {
		return roleid;
	}
	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}
	public String getRolename() {
		return rolename;
	}
	public void setRolename(String rolename) {
		this.rolename = rolename;
	}
	public String getDayforplr() {
		return dayforplr;
	}
	public void setDayforplr(String dayforplr) {
		this.dayforplr = dayforplr;
	}
	public ArrayList<TmEmployee> getTmployeelst() {
		return tmployeelst;
	}
	public void setTmployeelst(ArrayList<TmEmployee> tmployeelst) {
		this.tmployeelst = tmployeelst;
	}
	public int getRoleId() {
		return roleId;
	}
	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public Date getActualenddate() {
		return actualenddate;
	}
	public void setActualenddate(Date actualenddate) {
		this.actualenddate = actualenddate;
	}
	public Date getActualstartdate() {
		return actualstartdate;
	}
	public void setActualstartdate(Date actualstartdate) {
		this.actualstartdate = actualstartdate;
	}
	public int getDelayindays() {
		return delayindays;
	}
	public void setDelayindays(int delayindays) {
		this.delayindays = delayindays;
	}
	public Date getPlannedenddate() {
		return plannedenddate;
	}
	public void setPlannedenddate(Date plannedenddate) {
		this.plannedenddate = plannedenddate;
	}
	public Date getPlannedstartdate() {
		return plannedstartdate;
	}
	public void setPlannedstartdate(Date plannedstartdate) {
		this.plannedstartdate = plannedstartdate;
	}
	public int getStageid() {
		return stageid;
	}
	public void setStageid(int stageid) {
		this.stageid = stageid;
	}
	public String getStagename() {
		return stagename;
	}
	public void setStagename(String stagename) {
		this.stagename = stagename;
	}
	public String getStakeholdername() {
		return stakeholdername;
	}
	public void setStakeholdername(String stakeholdername) {
		this.stakeholdername = stakeholdername;
	}
	public String getStakeholderrole() {
		return stakeholderrole;
	}
	public void setStakeholderrole(String stakeholderrole) {
		this.stakeholderrole = stakeholderrole;
	}
	public int getTaskid() {
		return taskid;
	}
	public void setTaskid(int taskid) {
		this.taskid = taskid;
	}
	public String getTaskname() {
		return taskname;
	}
	public void setTaskname(String taskname) {
		this.taskname = taskname;
	}
/*	public PagingSorting getPaging() {
		return paging;
	}
	public void setPaging(PagingSorting paging) {
		this.paging = paging;
	}
	public String getSortBy() {
		return sortBy;
	}
	public void setSortBy(String sortBy) {
		this.sortBy = sortBy;
	}
	public String getSortByOrder() {
		return sortByOrder;
	}
	public void setSortByOrder(String sortByOrder) {
		this.sortByOrder = sortByOrder;
	}*/
	public PagingSorting getPagingSorting() {
		return pagingSorting;
	}
	public void setPagingSorting(PagingSorting pagingSorting) {
		this.pagingSorting = pagingSorting;
	}
	public String getSearchProjectPlanName() {
		return searchProjectPlanName;
	}
	public void setSearchProjectPlanName(String searchProjectPlanName) {
		this.searchProjectPlanName = searchProjectPlanName;
	}
	public String getSearchStageName() {
		return searchStageName;
	}
	public void setSearchStageName(String searchStageName) {
		this.searchStageName = searchStageName;
	}
	public String getProjectPlanId() {
		return projectPlanId;
	}
	public void setProjectPlanId(String projectPlanId) {
		this.projectPlanId = projectPlanId;
	}
	public String getSearchTaskName() {
		return searchTaskName;
	}
	public void setSearchTaskName(String searchTaskName) {
		this.searchTaskName = searchTaskName;
	}
	public String getDateFilter() {
		return dateFilter;
	}
	public void setDateFilter(String dateFilter) {
		this.dateFilter = dateFilter;
	}
	public String getFromDate() {
		return fromDate;
	}
	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}
	public String getToDate() {
		return toDate;
	}
	public void setToDate(String toDate) {
		this.toDate = toDate;
	}
	public String getSearchProjectId() {
		return searchProjectId;
	}
	public void setSearchProjectId(String searchProjectId) {
		this.searchProjectId = searchProjectId;
	}
	public Blob getRefdoc() {
		return refdoc;
	}
	public void setRefdoc(Blob refdoc) {
		this.refdoc = refdoc;
	}
	public String getDocName() {
		return docName;
	}
	public void setDocName(String docName) {
		this.docName = docName;
	}
	public int getProjectActionId() {
		return projectActionId;
	}
	public void setProjectActionId(int projectActionId) {
		this.projectActionId = projectActionId;
	}
	public int getProjectStatusFilter() {
		return projectStatusFilter;
	}
	public void setProjectStatusFilter(int projectStatusFilter) {
		this.projectStatusFilter = projectStatusFilter;
	}
	public String getSortBy() {
		return sortBy;
	}
	public void setSortBy(String sortBy) {
		this.sortBy = sortBy;
	}
	public String getSortByOrder() {
		return sortByOrder;
	}
	public void setSortByOrder(String sortByOrder) {
		this.sortByOrder = sortByOrder;
	}
	public TtrnProject getProjectDetails() {
		return projectDetails;
	}
	public void setProjectDetails(TtrnProject projectDetails) {
		this.projectDetails = projectDetails;
	}
	public String getStakeholderidlist() {
		return stakeholderidlist;
	}
	public void setStakeholderidlist(String stakeholderidlist) {
		this.stakeholderidlist = stakeholderidlist;
	}
	public int getPlannedduration() {
		return plannedduration;
	}
	public void setPlannedduration(int plannedduration) {
		this.plannedduration = plannedduration;
	}
	public FormFile getAttachment() {
		return attachment;
	}
	public void setAttachment(FormFile attachment) {
		this.attachment = attachment;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public String getRefDocName() {
		return refDocName;
	}
	public void setRefDocName(String refDocName) {
		this.refDocName = refDocName;
	}
	public String getVersion() {
		return version;
	}
	public void setVersion(String version) {
		this.version = version;
	}
	public Blob getAttachedFile() {
		return attachedFile;
	}
	public void setAttachedFile(Blob attachedFile) {
		this.attachedFile = attachedFile;
	}
	public String getStakeholderid() {
		return stakeholderid;
	}
	public void setStakeholderid(String stakeholderid) {
		this.stakeholderid = stakeholderid;
	}
	public String getSearchLaunchPriority() {
		return searchLaunchPriority;
	}
	public void setSearchLaunchPriority(String searchLaunchPriority) {
		this.searchLaunchPriority = searchLaunchPriority;
	}
	public int getIsupload() {
		return isupload;
	}
	public void setIsupload(int isupload) {
		this.isupload = isupload;
	}
	public String[] getEmployeeId() {
		return employeeId;
	}
	public void setEmployeeId(String[] employeeId) {
		this.employeeId = employeeId;
	}
	public String getMonthid() {
		return monthid;
	}
	public void setMonthid(String monthid) {
		this.monthid = monthid;
	}
	public String getMonthlabel() {
		return monthlabel;
	}
	public void setMonthlabel(String monthlabel) {
		this.monthlabel = monthlabel;
	}
	public ArrayList getMonthlst() {
		return monthlst;
	}
	public void setMonthlst(ArrayList monthlst) {
		this.monthlst = monthlst;
	}
	public String getMonthvalue() {
		return monthvalue;
	}
	public void setMonthvalue(String monthvalue) {
		this.monthvalue = monthvalue;
	}
	public String getSearchPlrId() {
		return searchPlrId;
	}
	public void setSearchPlrId(String searchPlrId) {
		this.searchPlrId = searchPlrId;
	}
	public String getEmployeelabel() {
		return employeelabel;
	}
	public void setEmployeelabel(String employeelabel) {
		this.employeelabel = employeelabel;
	}
	public String getEmployeevalue() {
		return employeevalue;
	}
	public void setEmployeevalue(String employeevalue) {
		this.employeevalue = employeevalue;
	}
	
}
