package com.ibm.ioes.npd.hibernate.beans;

// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.sql.Blob;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;

import com.ibm.ioes.npd.utilities.PagingSorting;


/**
 * TmAppconfig generated by hbm2java
 */

public class ProjectPlanReportDto  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int stageid ;
	private String stagename;
	private int taskid;
	private String taskname;
	private Date plannedstartdate;
	private Date plannedenddate;
	private Date actualstartdate;
	private Date actualenddate;
	private String stakeholderrole;
	private String stakeholdername;
	private int delayindays;
	
	private String projectPlanId;

	private String dateFilter=null;
	private String fromDate=null;
	private String toDate=null;
	private Blob refdoc;
	private String docName;
	private int projectActionId;
	private int projectStatusFilter;
	
	//private String sortBy=null;
	//private String sortByOrder=null;//getter and setter
	//PagingSorting paging=null;//setter and getter	
	
	PagingSorting pagingSorting=null;
	
	
	private String searchProjectPlanName;
	private String searchStageName;
	private String searchTaskName;
	private int searchProjectId;
	private String currentTaskStatus;
	private TtrnProject project;
	private String searchprojectid;
	private String searchprojectname;
		
	private String assignedtoname;
	private String assignedtoid;
	private String assignedtorolename;
	private String assignedtoroleid;
	private String actiontaken;
	private Date actiondate;
	private String actionremarks;
	private String rfitaskname;
	private String rfidocname;
	private String rfidocid;
	
	private int projectStatus;
	private int checkFlag;
	
	private int daysInProject;
	
	//ROHIT VERMA NEW CR
	private int taskDuration;
	private int taskCompDuration;
	private ArrayList<ProjectPlanReportDto> taskStatusList = new ArrayList<ProjectPlanReportDto>();
	private String taskCount;
	private ArrayList<ProjectPlanReportDto> taskDelayList = new ArrayList<ProjectPlanReportDto>();
	private String taskDelayCount;
	private String taskStatusString;
	private String taskDelayString;
	private ArrayList<ProjectPlanReportDto> taskInMonthList = new ArrayList<ProjectPlanReportDto>();
	private String totalTaskCount;
	private String month_Name;
	private String curTaskID;
	private String prvTaskID;
	private String file_Name_Chart;
	private int projectTaskCount;
	private String taskStatusQuery;
	private String taskDelayQuery;
	private String monthQuery;
	
	//rohit verma new crStart
	private String taskStatus;
	private String taskDelayValue;
	private HashMap<String, Integer> map_Stage_Color;
	
	public HashMap<String, Integer> getMap_Stage_Color() {
		return map_Stage_Color;
	}
	public void setMap_Stage_Color(HashMap<String, Integer> map_Stage_Color) {
		this.map_Stage_Color = map_Stage_Color;
	}
	public String getTaskDelayValue() {
		return taskDelayValue;
	}
	public void setTaskDelayValue(String taskDelayValue) {
		this.taskDelayValue = taskDelayValue;
	}
	public String getTaskStatus() {
		return taskStatus;
	}
	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus;
	}
//	rohit verma new CR Ends
	public String getFile_Name_Chart() {
		return file_Name_Chart;
	}
	public void setFile_Name_Chart(String file_Name_Chart) {
		this.file_Name_Chart = file_Name_Chart;
	}
	public String getMonth_Name() {
		return month_Name;
	}
	public void setMonth_Name(String month_Name) {
		this.month_Name = month_Name;
	}
	public ArrayList<ProjectPlanReportDto> getTaskInMonthList() {
		return taskInMonthList;
	}
	public void setTaskInMonthList(ArrayList<ProjectPlanReportDto> taskInMonthList) {
		this.taskInMonthList = taskInMonthList;
	}
	public String getTotalTaskCount() {
		return totalTaskCount;
	}
	public void setTotalTaskCount(String totalTaskCount) {
		this.totalTaskCount = totalTaskCount;
	}
	public ArrayList<ProjectPlanReportDto> getTaskStatusList() {
		return taskStatusList;
	}
	public void setTaskStatusList(ArrayList<ProjectPlanReportDto> taskStatusList) {
		this.taskStatusList = taskStatusList;
	}
	public int getTaskCompDuration() {
		return taskCompDuration;
	}
	public void setTaskCompDuration(int taskCompDuration) {
		this.taskCompDuration = taskCompDuration;
	}
	public int getTaskDuration() {
		return taskDuration;
	}
	public void setTaskDuration(int taskDuration) {
		this.taskDuration = taskDuration;
	}
	public int getDaysInProject() {
		return daysInProject;
	}
	public void setDaysInProject(int daysInProject) {
		this.daysInProject = daysInProject;
	}
	public int getProjectStatus() {
		return projectStatus;
	}
	public void setProjectStatus(int projectStatus) {
		this.projectStatus = projectStatus;
	}
	public Date getActiondate() {
		return actiondate;
	}
	public void setActiondate(Date actiondate) {
		this.actiondate = actiondate;
	}
	public String getActionremarks() {
		return actionremarks;
	}
	public void setActionremarks(String actionremarks) {
		this.actionremarks = actionremarks;
	}
	public String getActiontaken() {
		return actiontaken;
	}
	public void setActiontaken(String actiontaken) {
		this.actiontaken = actiontaken;
	}
	public String getAssignedtoid() {
		return assignedtoid;
	}
	public void setAssignedtoid(String assignedtoid) {
		this.assignedtoid = assignedtoid;
	}
	public String getAssignedtoname() {
		return assignedtoname;
	}
	public void setAssignedtoname(String assignedtoname) {
		this.assignedtoname = assignedtoname;
	}
	public String getAssignedtoroleid() {
		return assignedtoroleid;
	}
	public void setAssignedtoroleid(String assignedtoroleid) {
		this.assignedtoroleid = assignedtoroleid;
	}
	public String getAssignedtorolename() {
		return assignedtorolename;
	}
	public void setAssignedtorolename(String assignedtorolename) {
		this.assignedtorolename = assignedtorolename;
	}
	public String getCurrentTaskStatus() {
		return currentTaskStatus;
	}
	public void setCurrentTaskStatus(String currentTaskStatus) {
		this.currentTaskStatus = currentTaskStatus;
	}
	public Date getActualenddate() {
		return actualenddate;
	}
	public void setActualenddate(Date actualenddate) {
		this.actualenddate = actualenddate;
	}
	public Date getActualstartdate() {
		return actualstartdate;
	}
	public void setActualstartdate(Date actualstartdate) {
		this.actualstartdate = actualstartdate;
	}
	public int getDelayindays() {
		return delayindays;
	}
	public void setDelayindays(int delayindays) {
		this.delayindays = delayindays;
	}
	SimpleDateFormat sdf_GanttString=new SimpleDateFormat("dd/MM/yyyy"); 
	public Date getPlannedenddate() {
		return plannedenddate;
	}
	public String getPlannedenddateGanttString() {
		return sdf_GanttString.format(plannedenddate);
	}

	public void setPlannedenddate(Date plannedenddate) {
		this.plannedenddate = plannedenddate;
	}
	public Date getPlannedstartdate() {
		return plannedstartdate;
	}
	public String getPlannedstartdateGanttString() {
		return sdf_GanttString.format(plannedstartdate);
	}
	public void setPlannedstartdate(Date plannedstartdate) {
		this.plannedstartdate = plannedstartdate;
	}
	public int getStageid() {
		return stageid;
	}
	public void setStageid(int stageid) {
		this.stageid = stageid;
	}
	public String getStagename() {
		return stagename;
	}
	public void setStagename(String stagename) {
		this.stagename = stagename;
	}
	public String getStakeholdername() {
		return stakeholdername;
	}
	public void setStakeholdername(String stakeholdername) {
		this.stakeholdername = stakeholdername;
	}
	public String getStakeholderrole() {
		return stakeholderrole;
	}
	public void setStakeholderrole(String stakeholderrole) {
		this.stakeholderrole = stakeholderrole;
	}
	public int getTaskid() {
		return taskid;
	}
	public void setTaskid(int taskid) {
		this.taskid = taskid;
	}
	public String getTaskname() {
		return taskname;
	}
	public void setTaskname(String taskname) {
		this.taskname = taskname;
	}
/*	public PagingSorting getPaging() {
		return paging;
	}
	public void setPaging(PagingSorting paging) {
		this.paging = paging;
	}
	public String getSortBy() {
		return sortBy;
	}
	public void setSortBy(String sortBy) {
		this.sortBy = sortBy;
	}
	public String getSortByOrder() {
		return sortByOrder;
	}
	public void setSortByOrder(String sortByOrder) {
		this.sortByOrder = sortByOrder;
	}*/
	public PagingSorting getPagingSorting() {
		return pagingSorting;
	}
	public void setPagingSorting(PagingSorting pagingSorting) {
		this.pagingSorting = pagingSorting;
	}
	public String getSearchProjectPlanName() {
		return searchProjectPlanName;
	}
	public void setSearchProjectPlanName(String searchProjectPlanName) {
		this.searchProjectPlanName = searchProjectPlanName;
	}
	public String getSearchStageName() {
		return searchStageName;
	}
	public void setSearchStageName(String searchStageName) {
		this.searchStageName = searchStageName;
	}
	public String getProjectPlanId() {
		return projectPlanId;
	}
	public void setProjectPlanId(String projectPlanId) {
		this.projectPlanId = projectPlanId;
	}
	public String getSearchTaskName() {
		return searchTaskName;
	}
	public void setSearchTaskName(String searchTaskName) {
		this.searchTaskName = searchTaskName;
	}
	public String getDateFilter() {
		return dateFilter;
	}
	public void setDateFilter(String dateFilter) {
		this.dateFilter = dateFilter;
	}
	public String getFromDate() {
		return fromDate;
	}
	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}
	public String getToDate() {
		return toDate;
	}
	public void setToDate(String toDate) {
		this.toDate = toDate;
	}
	public int getSearchProjectId() {
		return searchProjectId;
	}
	public void setSearchProjectId(int searchProjectId) {
		this.searchProjectId = searchProjectId;
	}
	public Blob getRefdoc() {
		return refdoc;
	}
	public void setRefdoc(Blob refdoc) {
		this.refdoc = refdoc;
	}
	public String getDocName() {
		return docName;
	}
	public void setDocName(String docName) {
		this.docName = docName;
	}
	public int getProjectActionId() {
		return projectActionId;
	}
	public void setProjectActionId(int projectActionId) {
		this.projectActionId = projectActionId;
	}
	public int getProjectStatusFilter() {
		return projectStatusFilter;
	}
	public void setProjectStatusFilter(int projectStatusFilter) {
		this.projectStatusFilter = projectStatusFilter;
	}
	public TtrnProject getProject() {
		return project;
	}
	public void setProject(TtrnProject project) {
		this.project = project;
	}
	public String getSearchprojectid() {
		return searchprojectid;
	}
	public void setSearchprojectid(String searchprojectid) {
		this.searchprojectid = searchprojectid;
	}
	public String getSearchprojectname() {
		return searchprojectname;
	}
	public void setSearchprojectname(String searchprojectname) {
		this.searchprojectname = searchprojectname;
	}
	public String getRfitaskname() {
		return rfitaskname;
	}
	public void setRfitaskname(String rfitaskname) {
		this.rfitaskname = rfitaskname;
	}
	public String getRfidocname() {
		return rfidocname;
	}
	public void setRfidocname(String rfidocname) {
		this.rfidocname = rfidocname;
	}
	public String getRfidocid() {
		return rfidocid;
	}
	public void setRfidocid(String rfidocid) {
		this.rfidocid = rfidocid;
	}
	public int getCheckFlag() {
		return checkFlag;
	}
	public void setCheckFlag(int checkFlag) {
		this.checkFlag = checkFlag;
	}
	
	public String getActualenddateGanttString() 
	{
		if(actualenddate != null)
		{
			return sdf_GanttString.format(actualenddate);
		}
		else
		{
			return "";
		}
	}
	
	public String getActualstartdateGanttString() 
	{
		if(actualstartdate!= null)
		{
			return sdf_GanttString.format(actualstartdate);
		}
		else
		{
			return "";
		}
	}
	public String getTaskCount() {
		return taskCount;
	}
	public void setTaskCount(String taskCount) {
		this.taskCount = taskCount;
	}
	public String getTaskDelayCount() {
		return taskDelayCount;
	}
	public void setTaskDelayCount(String taskDelayCount) {
		this.taskDelayCount = taskDelayCount;
	}
	public ArrayList<ProjectPlanReportDto> getTaskDelayList() {
		return taskDelayList;
	}
	public void setTaskDelayList(ArrayList<ProjectPlanReportDto> taskDelayList) {
		this.taskDelayList = taskDelayList;
	}
	public String getTaskDelayString() {
		return taskDelayString;
	}
	public void setTaskDelayString(String taskDelayString) {
		this.taskDelayString = taskDelayString;
	}
	public String getTaskStatusString() {
		return taskStatusString;
	}
	public void setTaskStatusString(String taskStatusString) {
		this.taskStatusString = taskStatusString;
	}
	public String getCurTaskID() {
		return curTaskID;
	}
	public void setCurTaskID(String curTaskID) {
		this.curTaskID = curTaskID;
	}
	public String getPrvTaskID() {
		return prvTaskID;
	}
	public void setPrvTaskID(String prvTaskID) {
		this.prvTaskID = prvTaskID;
	}
	public int getProjectTaskCount() {
		return projectTaskCount;
	}
	public void setProjectTaskCount(int projectTaskCount) {
		this.projectTaskCount = projectTaskCount;
	}
	public String getTaskStatusQuery() {
		return taskStatusQuery;
	}
	public void setTaskStatusQuery(String taskStatusQuery) {
		this.taskStatusQuery = taskStatusQuery;
	}
	public String getTaskDelayQuery() {
		return taskDelayQuery;
	}
	public void setTaskDelayQuery(String taskDelayQuery) {
		this.taskDelayQuery = taskDelayQuery;
	}
	public String getMonthQuery() {
		return monthQuery;
	}
	public void setMonthQuery(String monthQuery) {
		this.monthQuery = monthQuery;
	}

}
