package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashMap;

import org.apache.struts.upload.FormFile;

import com.ibm.ioes.npd.utilities.PagingSorting;


/**
 * TmAppconfig generated by hbm2java
 */

public class ProjectDocsReportDto  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int stageid ;
	private String stagename;
	private int taskid;
	private String taskname;
	private Date plannedstartdate;
	private Date plannedenddate;
	private Date actualstartdate;
	private Date actualenddate;
	private String stakeholderrole;
	private String stakeholdername;
	private int delayindays;
	
	private String projectPlanId;

	private String dateFilter=null;
	private String fromDate=null;
	private String toDate=null;

	
	//private String sortBy=null;
	//private String sortByOrder=null;//getter and setter
	//PagingSorting paging=null;//setter and getter	
	
	PagingSorting pagingSorting=null;
	
	
	private String searchProjectPlanName;
	private String searchStageName;
	private String searchTaskName;
	private int searchProjectId;

	private FormFile attachment;
	private HashMap referenceDocList;
	private String[] referenceDocId;

	
	public Date getActualenddate() {
		return actualenddate;
	}
	public void setActualenddate(Date actualenddate) {
		this.actualenddate = actualenddate;
	}
	public Date getActualstartdate() {
		return actualstartdate;
	}
	public void setActualstartdate(Date actualstartdate) {
		this.actualstartdate = actualstartdate;
	}
	public int getDelayindays() {
		return delayindays;
	}
	public void setDelayindays(int delayindays) {
		this.delayindays = delayindays;
	}
	public Date getPlannedenddate() {
		return plannedenddate;
	}
	public void setPlannedenddate(Date plannedenddate) {
		this.plannedenddate = plannedenddate;
	}
	public Date getPlannedstartdate() {
		return plannedstartdate;
	}
	public void setPlannedstartdate(Date plannedstartdate) {
		this.plannedstartdate = plannedstartdate;
	}
	public int getStageid() {
		return stageid;
	}
	public void setStageid(int stageid) {
		this.stageid = stageid;
	}
	public String getStagename() {
		return stagename;
	}
	public void setStagename(String stagename) {
		this.stagename = stagename;
	}
	public String getStakeholdername() {
		return stakeholdername;
	}
	public void setStakeholdername(String stakeholdername) {
		this.stakeholdername = stakeholdername;
	}
	public String getStakeholderrole() {
		return stakeholderrole;
	}
	public void setStakeholderrole(String stakeholderrole) {
		this.stakeholderrole = stakeholderrole;
	}
	public int getTaskid() {
		return taskid;
	}
	public void setTaskid(int taskid) {
		this.taskid = taskid;
	}
	public String getTaskname() {
		return taskname;
	}
	public void setTaskname(String taskname) {
		this.taskname = taskname;
	}
/*	public PagingSorting getPaging() {
		return paging;
	}
	public void setPaging(PagingSorting paging) {
		this.paging = paging;
	}
	public String getSortBy() {
		return sortBy;
	}
	public void setSortBy(String sortBy) {
		this.sortBy = sortBy;
	}
	public String getSortByOrder() {
		return sortByOrder;
	}
	public void setSortByOrder(String sortByOrder) {
		this.sortByOrder = sortByOrder;
	}*/
	public PagingSorting getPagingSorting() {
		return pagingSorting;
	}
	public void setPagingSorting(PagingSorting pagingSorting) {
		this.pagingSorting = pagingSorting;
	}
	public String getSearchProjectPlanName() {
		return searchProjectPlanName;
	}
	public void setSearchProjectPlanName(String searchProjectPlanName) {
		this.searchProjectPlanName = searchProjectPlanName;
	}
	public String getSearchStageName() {
		return searchStageName;
	}
	public void setSearchStageName(String searchStageName) {
		this.searchStageName = searchStageName;
	}
	public String getProjectPlanId() {
		return projectPlanId;
	}
	public void setProjectPlanId(String projectPlanId) {
		this.projectPlanId = projectPlanId;
	}
	public String getSearchTaskName() {
		return searchTaskName;
	}
	public void setSearchTaskName(String searchTaskName) {
		this.searchTaskName = searchTaskName;
	}
	public String getDateFilter() {
		return dateFilter;
	}
	public void setDateFilter(String dateFilter) {
		this.dateFilter = dateFilter;
	}
	public String getFromDate() {
		return fromDate;
	}
	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}
	public String getToDate() {
		return toDate;
	}
	public void setToDate(String toDate) {
		this.toDate = toDate;
	}
	public int getSearchProjectId() {
		return searchProjectId;
	}
	public void setSearchProjectId(int searchProjectId) {
		this.searchProjectId = searchProjectId;
	}
	public FormFile getAttachment() {
		return attachment;
	}
	public void setAttachment(FormFile attachment) {
		this.attachment = attachment;
	}
	public String[] getReferenceDocId() {
		return referenceDocId;
	}
	public void setReferenceDocId(String[] referenceDocId) {
		this.referenceDocId = referenceDocId;
	}
	public HashMap getReferenceDocList() {
		return referenceDocList;
	}
	public void setReferenceDocList(HashMap referenceDocList) {
		this.referenceDocList = referenceDocList;
	}
	
}
