package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.sql.Blob;
import java.util.Date;

import com.ibm.ioes.npd.utilities.PagingSorting;


/**
 * TmAppconfig generated by hbm2java
 */

public class QueryBuilderDto  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String Col1;
	private String Col2;
	private String Col3;
	private String Col4;
	private String Col5;
	private String Col6;
	private String Col7;
	private String Col8;
	private String Col9;
	private String Col10;
	private String Col11;
	private String Col12;
	private String Col13;
	private String Col14;
	private String Col15;
	private String Col16;
	private String Col17;
	private String Col18;
	private String Col19;
	private String Col21;
	private String Col22;
	private String Col23;
	private String Col24;
	private String Col25;
	private String Col26;
	private String Col27;
	private String Col28;
	private String Col29;
	private String Col30;
	private String Col31;
	private String Col32;
	private String Col33;
	private String Col34;
	private String Col35;
	private String Col36;
	private String Col37;
	private String Col38;
	private String Col39;
	private String Col40;
	private String Col41;
	private String Col42;
	private String Col43;
	private String Col44;
	private String Col45;
	private String Col46;
	private String Col47;
	private String Col48;
	private String Col49;
	private String Col50;
	private String Col51;
	private String Col52;
	private String Col53;
	private String Col54;
	private String Col55;
	private String Col56;
	private String Col57;
	private String Col58;
	private String Col59;

	private String query;
	
	public String getQuery() {
	    return query;
	}
	public void setQuery(String query) {
	    this.query = query;
	}
	public static long getSerialVersionUID() {
		return serialVersionUID;
	}
	public String getCol1() {
		return Col1;
	}
	public void setCol1(String col1) {
		Col1 = col1;
	}
	public String getCol10() {
		return Col10;
	}
	public void setCol10(String col10) {
		Col10 = col10;
	}
	public String getCol11() {
		return Col11;
	}
	public void setCol11(String col11) {
		Col11 = col11;
	}
	public String getCol12() {
		return Col12;
	}
	public void setCol12(String col12) {
		Col12 = col12;
	}
	public String getCol13() {
		return Col13;
	}
	public void setCol13(String col13) {
		Col13 = col13;
	}
	public String getCol14() {
		return Col14;
	}
	public void setCol14(String col14) {
		Col14 = col14;
	}
	public String getCol15() {
		return Col15;
	}
	public void setCol15(String col15) {
		Col15 = col15;
	}
	public String getCol16() {
		return Col16;
	}
	public void setCol16(String col16) {
		Col16 = col16;
	}
	public String getCol17() {
		return Col17;
	}
	public void setCol17(String col17) {
		Col17 = col17;
	}
	public String getCol18() {
		return Col18;
	}
	public void setCol18(String col18) {
		Col18 = col18;
	}
	public String getCol19() {
		return Col19;
	}
	public void setCol19(String col19) {
		Col19 = col19;
	}
	public String getCol2() {
		return Col2;
	}
	public void setCol2(String col2) {
		Col2 = col2;
	}
	public String getCol21() {
		return Col21;
	}
	public void setCol21(String col21) {
		Col21 = col21;
	}
	public String getCol22() {
		return Col22;
	}
	public void setCol22(String col22) {
		Col22 = col22;
	}
	public String getCol23() {
		return Col23;
	}
	public void setCol23(String col23) {
		Col23 = col23;
	}
	public String getCol24() {
		return Col24;
	}
	public void setCol24(String col24) {
		Col24 = col24;
	}
	public String getCol25() {
		return Col25;
	}
	public void setCol25(String col25) {
		Col25 = col25;
	}
	public String getCol26() {
		return Col26;
	}
	public void setCol26(String col26) {
		Col26 = col26;
	}
	public String getCol27() {
		return Col27;
	}
	public void setCol27(String col27) {
		Col27 = col27;
	}
	public String getCol28() {
		return Col28;
	}
	public void setCol28(String col28) {
		Col28 = col28;
	}
	public String getCol29() {
		return Col29;
	}
	public void setCol29(String col29) {
		Col29 = col29;
	}
	public String getCol3() {
		return Col3;
	}
	public void setCol3(String col3) {
		Col3 = col3;
	}
	public String getCol30() {
		return Col30;
	}
	public void setCol30(String col30) {
		Col30 = col30;
	}
	public String getCol31() {
		return Col31;
	}
	public void setCol31(String col31) {
		Col31 = col31;
	}
	public String getCol32() {
		return Col32;
	}
	public void setCol32(String col32) {
		Col32 = col32;
	}
	public String getCol33() {
		return Col33;
	}
	public void setCol33(String col33) {
		Col33 = col33;
	}
	public String getCol34() {
		return Col34;
	}
	public void setCol34(String col34) {
		Col34 = col34;
	}
	public String getCol35() {
		return Col35;
	}
	public void setCol35(String col35) {
		Col35 = col35;
	}
	public String getCol36() {
		return Col36;
	}
	public void setCol36(String col36) {
		Col36 = col36;
	}
	public String getCol37() {
		return Col37;
	}
	public void setCol37(String col37) {
		Col37 = col37;
	}
	public String getCol38() {
		return Col38;
	}
	public void setCol38(String col38) {
		Col38 = col38;
	}
	public String getCol39() {
		return Col39;
	}
	public void setCol39(String col39) {
		Col39 = col39;
	}
	public String getCol4() {
		return Col4;
	}
	public void setCol4(String col4) {
		Col4 = col4;
	}
	public String getCol40() {
		return Col40;
	}
	public void setCol40(String col40) {
		Col40 = col40;
	}
	public String getCol41() {
		return Col41;
	}
	public void setCol41(String col41) {
		Col41 = col41;
	}
	public String getCol42() {
		return Col42;
	}
	public void setCol42(String col42) {
		Col42 = col42;
	}
	public String getCol43() {
		return Col43;
	}
	public void setCol43(String col43) {
		Col43 = col43;
	}
	public String getCol44() {
		return Col44;
	}
	public void setCol44(String col44) {
		Col44 = col44;
	}
	public String getCol45() {
		return Col45;
	}
	public void setCol45(String col45) {
		Col45 = col45;
	}
	public String getCol46() {
		return Col46;
	}
	public void setCol46(String col46) {
		Col46 = col46;
	}
	public String getCol47() {
		return Col47;
	}
	public void setCol47(String col47) {
		Col47 = col47;
	}
	public String getCol48() {
		return Col48;
	}
	public void setCol48(String col48) {
		Col48 = col48;
	}
	public String getCol49() {
		return Col49;
	}
	public void setCol49(String col49) {
		Col49 = col49;
	}
	public String getCol5() {
		return Col5;
	}
	public void setCol5(String col5) {
		Col5 = col5;
	}
	public String getCol50() {
		return Col50;
	}
	public void setCol50(String col50) {
		Col50 = col50;
	}
	public String getCol51() {
		return Col51;
	}
	public void setCol51(String col51) {
		Col51 = col51;
	}
	public String getCol52() {
		return Col52;
	}
	public void setCol52(String col52) {
		Col52 = col52;
	}
	public String getCol53() {
		return Col53;
	}
	public void setCol53(String col53) {
		Col53 = col53;
	}
	public String getCol54() {
		return Col54;
	}
	public void setCol54(String col54) {
		Col54 = col54;
	}
	public String getCol55() {
		return Col55;
	}
	public void setCol55(String col55) {
		Col55 = col55;
	}
	public String getCol56() {
		return Col56;
	}
	public void setCol56(String col56) {
		Col56 = col56;
	}
	public String getCol57() {
		return Col57;
	}
	public void setCol57(String col57) {
		Col57 = col57;
	}
	public String getCol58() {
		return Col58;
	}
	public void setCol58(String col58) {
		Col58 = col58;
	}
	public String getCol59() {
		return Col59;
	}
	public void setCol59(String col59) {
		Col59 = col59;
	}
	public String getCol6() {
		return Col6;
	}
	public void setCol6(String col6) {
		Col6 = col6;
	}
	public String getCol7() {
		return Col7;
	}
	public void setCol7(String col7) {
		Col7 = col7;
	}
	public String getCol8() {
		return Col8;
	}
	public void setCol8(String col8) {
		Col8 = col8;
	}
	public String getCol9() {
		return Col9;
	}
	public void setCol9(String col9) {
		Col9 = col9;
	}
	
}
