package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TmAppconfig generated by hbm2java
 */

public class TmAppconfig  implements java.io.Serializable {


    // Fields    

     private int appconfigid;
     private String keyname;
     private String keyvalue;
     private long cretaedby;
     private Date createddate;


    // Constructors

    /** default constructor */
    public TmAppconfig() {
    }

    
    /** full constructor */
    public TmAppconfig(int appconfigid, String keyname, String keyvalue, long cretaedby, Date createddate) {
        this.appconfigid = appconfigid;
        this.keyname = keyname;
        this.keyvalue = keyvalue;
        this.cretaedby = cretaedby;
        this.createddate = createddate;
    }
    

   
    // Property accessors

    public int getAppconfigid() {
        return this.appconfigid;
    }
    
    public void setAppconfigid(int appconfigid) {
        this.appconfigid = appconfigid;
    }

    public String getKeyname() {
        return this.keyname;
    }
    
    public void setKeyname(String keyname) {
        this.keyname = keyname;
    }

    public String getKeyvalue() {
        return this.keyvalue;
    }
    
    public void setKeyvalue(String keyvalue) {
        this.keyvalue = keyvalue;
    }

    public long getCretaedby() {
        return this.cretaedby;
    }
    
    public void setCretaedby(long cretaedby) {
        this.cretaedby = cretaedby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
   








}
