package com.ibm.ioes.npd.hibernate.beans;

import java.util.Date;
// Generated Feb 8, 2010 10:44:50 AM by Hibernate Tools 3.1.0.beta4

import com.ibm.ioes.npd.utilities.PagingSorting;



/**
 * TmEmployeeRoleHistory generated by hbm2java
 */

public class TmEmployeeRoleHistory  implements java.io.Serializable {


    // Fields    

     private int id;
     private TmEmployee employeeid;
     private Date createddate;
     private Integer oldlevel1;
     private Integer oldlevel2;
     private Integer newlevel1;
     private Integer newlevel2;
     private String oldroles;
     private String newroles;
     PagingSorting pagingSorting = null;

     private Long oldlevel1employee;
     private Long oldlevel2employee;
     private Long newlevel1employee;
     private Long newlevel2employee;

    // Constructors

    /** default constructor */
    public TmEmployeeRoleHistory() {
    }

	/** minimal constructor */
    public TmEmployeeRoleHistory(int id) {
        this.id = id;
    }
    
    /** full constructor */
    public TmEmployeeRoleHistory(int id, String oldroles, TmEmployee employeeid,Date createddate,String newroles,Integer oldlevel1,Integer oldlevel2,Integer newlevel1,Integer newlevel2) {
        this.id = id;
        this.oldroles = oldroles;
        this.newroles = newroles;
        this.employeeid = employeeid;
        this.createddate=createddate;
        this.oldlevel1=oldlevel1;
        this.oldlevel2=oldlevel2;
        this.newlevel1=newlevel1;
        this.newlevel2=newlevel2;
    }
    

   
    // Property accessors

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }



	public TmEmployee getEmployeeid() {
		return employeeid;
	}

	public void setEmployeeid(TmEmployee employeeid) {
		this.employeeid = employeeid;
	}

	public Date getCreateddate() {
		return createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Integer getNewlevel2() {
		return newlevel2;
	}

	public void setNewlevel2(Integer newlevel2) {
		this.newlevel2 = newlevel2;
	}

	public String getNewroles() {
		return newroles;
	}

	public void setNewroles(String newroles) {
		this.newroles = newroles;
	}

	public Integer getOldlevel1() {
		return oldlevel1;
	}

	public void setOldlevel1(Integer oldlevel1) {
		this.oldlevel1 = oldlevel1;
	}

	public Integer getOldlevel2() {
		return oldlevel2;
	}

	public void setOldlevel2(Integer oldlevel2) {
		this.oldlevel2 = oldlevel2;
	}

	public String getOldroles() {
		return oldroles;
	}

	public void setOldroles(String oldroles) {
		this.oldroles = oldroles;
	}

	public Integer getNewlevel1() {
		return newlevel1;
	}

	public void setNewlevel1(Integer newlevel1) {
		this.newlevel1 = newlevel1;
	}

	public PagingSorting getPagingSorting() {
		return pagingSorting;
	}

	public void setPagingSorting(PagingSorting pagingSorting) {
		this.pagingSorting = pagingSorting;
	}

	public Long getNewlevel1employee() {
		return newlevel1employee;
	}

	public void setNewlevel1employee(Long newlevel1employee) {
		this.newlevel1employee = newlevel1employee;
	}

	public Long getNewlevel2employee() {
		return newlevel2employee;
	}

	public void setNewlevel2employee(Long newlevel2employee) {
		this.newlevel2employee = newlevel2employee;
	}

	public Long getOldlevel1employee() {
		return oldlevel1employee;
	}

	public void setOldlevel1employee(Long oldlevel1employee) {
		this.oldlevel1employee = oldlevel1employee;
	}

	public Long getOldlevel2employee() {
		return oldlevel2employee;
	}

	public void setOldlevel2employee(Long oldlevel2employee) {
		this.oldlevel2employee = oldlevel2employee;
	}

	







}
