package com.ibm.ioes.npd.hibernate.beans;

// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TmEmployee generated by hbm2java
 */

public class TmEmployee implements java.io.Serializable {

	// Fields

	private long npdempid;

	private long empid;

	private String empname;

	private int empsource;

	private long createdby;

	private Date createddate;

	private Long modifiedby;

	private Date modifieddate;

	private int isactive;

	private TmRoles level1; 
	 
	private TmRoles level2; 
	
	private String email;

	private Long oneRoleId;
	
	private long currentRoleId;
	
	private String currentRoleName;
	
	private Long level1employeeid; 
	 
	private Long level2employeeid;
	
	private String mobileNo; 
	
	private String hrms_employee_number=null;
	
	private String hrms_full_name=null;
	
	private String hrms_email=null;
	
	private String level1id=null;
	
	private String level2id=null;
	private String ssfid; 
	
	// Constructors

	public long getCurrentRoleId() {
		return currentRoleId;
	}

	public void setCurrentRoleId(long currentRoleId) {
		this.currentRoleId = currentRoleId;
	}

	public String getCurrentRoleName() {
		return currentRoleName;
	}

	public void setCurrentRoleName(String currentRoleName) {
		this.currentRoleName = currentRoleName;
	}

	/** default constructor */
	public TmEmployee() {
	}

	/** minimal constructor */
	public TmEmployee(long npdempid, long empid, String empname, int empsource,
			long createdby, Date createddate, int isactive, String SSF_ID) {
		this.npdempid = npdempid;
		this.empid = empid;
		this.empname = empname;
		this.empsource = empsource;
		this.createdby = createdby;
		this.createddate = createddate;
		this.isactive = isactive;
		this.ssfid=SSF_ID;
	}

	/** full constructor */
	public TmEmployee(long npdempid, long empid, String empname, int empsource,
			long createdby, Date createddate, Long modifiedby,
			Date modifieddate, int isactive, Set tmEmpescalationmatrixes,
			Set tmRoleempmappings, String SSF_ID) {
		this.npdempid = npdempid;
		this.empid = empid;
		this.empname = empname;
		this.empsource = empsource;
		this.createdby = createdby;
		this.createddate = createddate;
		this.modifiedby = modifiedby;
		this.modifieddate = modifieddate;
		this.isactive = isactive;
		this.ssfid=SSF_ID;
	}

	// Property accessors

	public String getEmpname() {
		return this.empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	public int getEmpsource() {
		return this.empsource;
	}

	public void setEmpsource(int empsource) {
		this.empsource = empsource;
	}

	public long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(long createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Long getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(Long modifiedby) {
		this.modifiedby = modifiedby;
	}

	public Date getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	public int getIsactive() {
		return this.isactive;
	}

	public void setIsactive(int isactive) {
		this.isactive = isactive;
	}

	/**
	 * @return the empid
	 */
	public long getEmpid() {
		return empid;
	}

	/**
	 * @param empid
	 *            the empid to set
	 */
	public void setEmpid(long empid) {
		this.empid = empid;
	}

	/**
	 * @return the npdempid
	 */
	public long getNpdempid() {
		return npdempid;
	}

	/**
	 * @param npdempid
	 *            the npdempid to set
	 */
	public void setNpdempid(long npdempid) {
		this.npdempid = npdempid;
	}

	/**
	 * @return the level1
	 */
	public TmRoles getLevel1() {
		return level1;
	}

	/**
	 * @param level1 the level1 to set
	 */
	public void setLevel1(TmRoles level1) {
		this.level1 = level1;
	}

	/**
	 * @return the level2
	 */
	public TmRoles getLevel2() {
		return level2;
	}

	/**
	 * @param level2 the level2 to set
	 */
	public void setLevel2(TmRoles level2) {
		this.level2 = level2;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	public Long getOneRoleId() {
		return oneRoleId;
	}

	public void setOneRoleId(Long oneRoleId) {
		this.oneRoleId = oneRoleId;
	}

	public Long getLevel1employeeid() {
		return level1employeeid;
	}

	public void setLevel1employeeid(Long level1employeeid) {
		this.level1employeeid = level1employeeid;
	}
	
	public Long getLevel2employeeid() {
		return level2employeeid;
	}

	public void setLevel2employeeid(Long level2employeeid) {
		this.level2employeeid = level2employeeid;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getHrms_employee_number() {
		return hrms_employee_number;
	}

	public void setHrms_employee_number(String hrms_employee_number) {
		this.hrms_employee_number = hrms_employee_number;
	}

	public String getHrms_full_name() {
		return hrms_full_name;
	}

	public void setHrms_full_name(String hrms_full_name) {
		this.hrms_full_name = hrms_full_name;
	}

	public String getHrms_email() {
		return hrms_email;
	}
	public void setHrms_email(String hrms_email) {
		this.hrms_email = hrms_email;
	}
	public String getSsfid() {
		return ssfid;
	}

	public void setSsfid(String ssfid) {
		this.ssfid = ssfid;
	}

	public String getLevel1id() {
		return level1id;
	}

	public void setLevel1id(String level1id) {
		this.level1id = level1id;
	}

	public String getLevel2id() {
		return level2id;
	}

	public void setLevel2id(String level2id) {
		this.level2id = level2id;
	}

	

	
}
