package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TmMeetings generated by hbm2java
 */

public class TmMeetings  implements java.io.Serializable {


    // Fields    

     private int meetingtypeid;
     private String meetingtype;
     private int isactive;
     private long createdby;
     private Date createddate;
     private Long modifiedby;
     private Date modifieddate;
   

    // Constructors

    /** default constructor */
    public TmMeetings() {
    }

	/** minimal constructor */
    public TmMeetings(int meetingtypeid, String meetingtype, int isactive, long createdby, Date createddate) {
        this.meetingtypeid = meetingtypeid;
        this.meetingtype = meetingtype;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
    }
    
    /** full constructor */
    public TmMeetings(int meetingtypeid, String meetingtype, int isactive, long createdby, Date createddate, Long modifiedby, Date modifieddate, Set ttrnMeetingmomses, Set ttrnMeetingscheduleses) {
        this.meetingtypeid = meetingtypeid;
        this.meetingtype = meetingtype;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
       
    }
    

   
    // Property accessors

    public int getMeetingtypeid() {
        return this.meetingtypeid;
    }
    
    public void setMeetingtypeid(int meetingtypeid) {
        this.meetingtypeid = meetingtypeid;
    }

    public String getMeetingtype() {
        return this.meetingtype;
    }
    
    public void setMeetingtype(String meetingtype) {
        this.meetingtype = meetingtype;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

  

}
