package com.ibm.ioes.npd.hibernate.beans;

// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;

/**
 * TmWorkflowtasks generated by hbm2java
 */

public class TmMultipleTaskMapping implements java.io.Serializable {

	// Fields

	private long id;

	private long taskid;

	private long previousTaskId;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getPreviousTaskId() {
		return previousTaskId;
	}

	public void setPreviousTaskId(long previousTaskId) {
		this.previousTaskId = previousTaskId;
	}

	public long getTaskid() {
		return taskid;
	}

	public void setTaskid(long taskid) {
		this.taskid = taskid;
	}


		
	// Constructors

	


}
