package com.ibm.ioes.npd.hibernate.beans;
// Generated Jan 12, 2010 4:57:25 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TmNpdcategory generated by hbm2java
 */

public class TmNpdcategory  implements java.io.Serializable {


    // Fields    

     private int npdcatid;
     private String npdcatdesc;
     private int isactive;
     private Date createddate;
     private long createdby;
     private Date modifieddate;
     private Long modifiedby;


    // Constructors

    /** default constructor */
    public TmNpdcategory() {
    }

	/** minimal constructor */
    public TmNpdcategory(int npdcatid, String npdcatdesc, int isactive, Date createddate, long createdby) {
        this.npdcatid = npdcatid;
        this.npdcatdesc = npdcatdesc;
        this.isactive = isactive;
        this.createddate = createddate;
        this.createdby = createdby;
    }
    
    /** full constructor */
    public TmNpdcategory(int npdcatid, String npdcatdesc, int isactive, Date createddate, long createdby, Date modifieddate, Long modifiedby) {
        this.npdcatid = npdcatid;
        this.npdcatdesc = npdcatdesc;
        this.isactive = isactive;
        this.createddate = createddate;
        this.createdby = createdby;
        this.modifieddate = modifieddate;
        this.modifiedby = modifiedby;
    }
    

   
    // Property accessors

    public int getNpdcatid() {
        return this.npdcatid;
    }
    
    public void setNpdcatid(int npdcatid) {
        this.npdcatid = npdcatid;
    }

    public String getNpdcatdesc() {
        return this.npdcatdesc;
    }
    
    public void setNpdcatdesc(String npdcatdesc) {
        this.npdcatdesc = npdcatdesc;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
   








}
