package com.ibm.ioes.npd.hibernate.beans;
// Generated Jan 12, 2010 4:57:24 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TmProductcategory generated by hbm2java
 */

public class TmProductcategory  implements java.io.Serializable {


    // Fields    

     private int prodcatid;
     private String prodcatdesc;
     private int isactive;
     private Date createddate;
     private long createdby;
     private Date modifieddate;
     private Long modifiedby;


    // Constructors

    /** default constructor */
    public TmProductcategory() {
    }

	/** minimal constructor */
    public TmProductcategory(int prodcatid, String prodcatdesc, int isactive, Date createddate, long createdby) {
        this.prodcatid = prodcatid;
        this.prodcatdesc = prodcatdesc;
        this.isactive = isactive;
        this.createddate = createddate;
        this.createdby = createdby;
    }
    
    /** full constructor */
    public TmProductcategory(int prodcatid, String prodcatdesc, int isactive, Date createddate, long createdby, Date modifieddate, Long modifiedby) {
        this.prodcatid = prodcatid;
        this.prodcatdesc = prodcatdesc;
        this.isactive = isactive;
        this.createddate = createddate;
        this.createdby = createdby;
        this.modifieddate = modifieddate;
        this.modifiedby = modifiedby;
    }
    

   
    // Property accessors

    public int getProdcatid() {
        return this.prodcatid;
    }
    
    public void setProdcatid(int prodcatid) {
        this.prodcatid = prodcatid;
    }

    public String getProdcatdesc() {
        return this.prodcatdesc;
    }
    
    public void setProdcatdesc(String prodcatdesc) {
        this.prodcatdesc = prodcatdesc;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
   








}
