package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TmRoles generated by hbm2java
 */

public class TmRoles  implements java.io.Serializable {


    // Fields    

     private int roleid;
     private String rolename;
     private int isactive;
     private long createdby;
     private Date createddate;
     private Long modifiedby;
     private Date modifieddate;
     private Set tmRoleempmappings = new HashSet(0);


    // Constructors

    /** default constructor */
    public TmRoles() {
    }

	/** minimal constructor */
    public TmRoles(int roleid, String rolename, int isactive, long createdby, Date createddate) {
        this.roleid = roleid;
        this.rolename = rolename;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
    }
    
    /** full constructor */
    public TmRoles(int roleid, String rolename, int isactive, long createdby, Date createddate, Long modifiedby, Date modifieddate, Set tmRoleempmappings) {
        this.roleid = roleid;
        this.rolename = rolename;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
        this.tmRoleempmappings = tmRoleempmappings;
    }
    

   
    // Property accessors

    public int getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(int roleid) {
        this.roleid = roleid;
    }

    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public Set getTmRoleempmappings() {
        return this.tmRoleempmappings;
    }
    
    public void setTmRoleempmappings(Set tmRoleempmappings) {
        this.tmRoleempmappings = tmRoleempmappings;
    }
   








}
