package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TmRoleempmapping generated by hbm2java
 */

public class TmRoleempmapping  implements java.io.Serializable {


    // Fields    

     private long roleempid;
     private TmRoles tmRoles;
     private TmEmployee tmEmployee;
     private int isactive;
     private long createdby;
     private Date createddate;
     private Long modifiedby;
     private Date modifieddate;


    // Constructors

    /** default constructor */
    public TmRoleempmapping() {
    }

	/** minimal constructor */
    public TmRoleempmapping(long roleempid, TmRoles tmRoles, TmEmployee tmEmployee, int isactive, long createdby, Date createddate) {
        this.roleempid = roleempid;
        this.tmRoles = tmRoles;
        this.tmEmployee = tmEmployee;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
    }
    
    /** full constructor */
    public TmRoleempmapping(long roleempid, TmRoles tmRoles, TmEmployee tmEmployee, int isactive, long createdby, Date createddate, Long modifiedby, Date modifieddate) {
        this.roleempid = roleempid;
        this.tmRoles = tmRoles;
        this.tmEmployee = tmEmployee;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
    }
    

   
    // Property accessors

    public long getRoleempid() {
        return this.roleempid;
    }
    
    public void setRoleempid(long roleempid) {
        this.roleempid = roleempid;
    }

    public TmRoles getTmRoles() {
        return this.tmRoles;
    }
    
    public void setTmRoles(TmRoles tmRoles) {
        this.tmRoles = tmRoles;
    }

    public TmEmployee getTmEmployee() {
        return this.tmEmployee;
    }
    
    public void setTmEmployee(TmEmployee tmEmployee) {
        this.tmEmployee = tmEmployee;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
   








}
