package com.ibm.ioes.npd.hibernate.beans;

// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;

/**
 * TmWorkflowtasks generated by hbm2java
 */

public class TmstProjecthierarchytasksflow implements java.io.Serializable {

	// Fields
	
	private long prevtaskdetails;
	
	private long projectworkflowid;
	
	private long taskid;
	
	private long prevtaskid;
	
	private String prevTaskName=null;

	

	// Constructors

	/** default constructor */
	public TmstProjecthierarchytasksflow() {
	}
	
	/** full constructor */
	public TmstProjecthierarchytasksflow(long prevtaskdetails,long projrctworkflowid,long taskid,long prevtaskid ) {
		this.prevtaskdetails = prevtaskdetails;
		this.projectworkflowid = projectworkflowid;
		this.taskid = taskid;
		this.prevtaskid = prevtaskid;
		
	}

	public long getPrevtaskdetails() {
		return prevtaskdetails;
	}

	public void setPrevtaskdetails(long prevtaskdetails) {
		this.prevtaskdetails = prevtaskdetails;
	}

	public long getPrevtaskid() {
		return prevtaskid;
	}

	public void setPrevtaskid(long prevtaskid) {
		this.prevtaskid = prevtaskid;
	}


	public long getTaskid() {
		return taskid;
	}

	public void setTaskid(long taskid) {
		this.taskid = taskid;
	}

	public long getProjectworkflowid() {
		return projectworkflowid;
	}

	public void setProjectworkflowid(long projectworkflowid) {
		this.projectworkflowid = projectworkflowid;
	}

	public String getPrevTaskName() {
		return prevTaskName;
	}

	public void setPrevTaskName(String prevTaskName) {
		this.prevTaskName = prevTaskName;
	}

	

}
