package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TmWorkflowparameterdetails generated by hbm2java
 */

public class TmWorkflowparameterdetails  implements java.io.Serializable {


    // Fields    

     private long parameterdetailid;
     private String parametervalue;
     private int parameterid;
     private int createdby;
     private Date createddate;
     private Integer modifiedby;
     private Date modifieddate;
     private int isactive;


    // Constructors

    /** default constructor */
    public TmWorkflowparameterdetails() {
    }

	/** minimal constructor */
    public TmWorkflowparameterdetails(long parameterdetailid, int parameterid, int createdby, Date createddate, int isactive) {
        this.parameterdetailid = parameterdetailid;
        this.parameterid = parameterid;
        this.createdby = createdby;
        this.createddate = createddate;
        this.isactive = isactive;
    }
    
    /** full constructor */
    public TmWorkflowparameterdetails(long parameterdetailid, String parametervalue, int parameterid, int createdby, Date createddate, Integer modifiedby, Date modifieddate, int isactive) {
        this.parameterdetailid = parameterdetailid;
        this.parametervalue = parametervalue;
        this.parameterid = parameterid;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
        this.isactive = isactive;
    }
    

   
    // Property accessors

    public long getParameterdetailid() {
        return this.parameterdetailid;
    }
    
    public void setParameterdetailid(long parameterdetailid) {
        this.parameterdetailid = parameterdetailid;
    }

    public String getParametervalue() {
        return this.parametervalue;
    }
    
    public void setParametervalue(String parametervalue) {
        this.parametervalue = parametervalue;
    }

    public int getParameterid() {
        return this.parameterid;
    }
    
    public void setParameterid(int parameterid) {
        this.parameterid = parameterid;
    }

    public int getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }
   








}
