package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TmWorkflowstage generated by hbm2java
 */

public class TmWorkflowstageHistory  implements java.io.Serializable {


    // Fields    
	 private int id;	
     private int stageid;
     private int workflow1;
     private String stagename;
     private String stagedesc;
     private int createdby;
     private Date createddate;
     private Integer modifiedby;
     private Date modifieddate;
     private int isactive;
     private TmWorkflowHistory workflowhistoryid;



	public TmWorkflowHistory getWorkflowhistoryid() {
		return workflowhistoryid;
	}

	public void setWorkflowhistoryid(TmWorkflowHistory workflowhistoryid) {
		this.workflowhistoryid = workflowhistoryid;
	}

	/** default constructor */
    public TmWorkflowstageHistory() {
    }

	/** minimal constructor */
    public TmWorkflowstageHistory(int stageid, int workflow1, int createdby, Date createddate, int isactive) {
        this.stageid = stageid;
        this.workflow1 = workflow1;
        this.createdby = createdby;
        this.createddate = createddate;
        this.isactive = isactive;
    }
    
    /** full constructor */
    public TmWorkflowstageHistory(int stageid,int workflow1, String stagename, String stagedesc, int createdby, Date createddate, Integer modifiedby, Date modifieddate, int isactive) {
        this.stageid = stageid;
        this.workflow1 = workflow1;
        this.stagename = stagename;
        this.stagedesc = stagedesc;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
        this.isactive = isactive;
    }
    

   
    // Property accessors

    public int getStageid() {
        return this.stageid;
    }
    
    public void setStageid(int stageid) {
        this.stageid = stageid;
    }


	public int getWorkflow1() {
		return workflow1;
	}

	public void setWorkflow1(int workflow1) {
		this.workflow1 = workflow1;
	}

	public String getStagename() {
        return this.stagename;
    }
    
    public void setStagename(String stagename) {
        this.stagename = stagename;
    }

    public String getStagedesc() {
        return this.stagedesc;
    }
    
    public void setStagedesc(String stagedesc) {
        this.stagedesc = stagedesc;
    }

    public int getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
   








}
