package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TmWorkflowparameters generated by hbm2java
 */

public class TmWorkflowparameters  implements java.io.Serializable {


    // Fields    

     private int parameterid;
     private Integer parametertype;
     private String parametername;
     private String parameterdesc;
     private Integer parameterforid;
     private Date createddate;
     private Integer modifiedby;
     private Date modifieddate;
     private int isactive;


    // Constructors

    /** default constructor */
    public TmWorkflowparameters() {
    }

	/** minimal constructor */
    public TmWorkflowparameters(int parameterid, Date createddate, int isactive) {
        this.parameterid = parameterid;
        this.createddate = createddate;
        this.isactive = isactive;
    }
    
    /** full constructor */
    public TmWorkflowparameters(int parameterid, Integer parametertype, String parametername, String parameterdesc, Integer parameterforid, Date createddate, Integer modifiedby, Date modifieddate, int isactive) {
        this.parameterid = parameterid;
        this.parametertype = parametertype;
        this.parametername = parametername;
        this.parameterdesc = parameterdesc;
        this.parameterforid = parameterforid;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
        this.isactive = isactive;
    }
    

   
    // Property accessors

    public int getParameterid() {
        return this.parameterid;
    }
    
    public void setParameterid(int parameterid) {
        this.parameterid = parameterid;
    }

    public Integer getParametertype() {
        return this.parametertype;
    }
    
    public void setParametertype(Integer parametertype) {
        this.parametertype = parametertype;
    }

    public String getParametername() {
        return this.parametername;
    }
    
    public void setParametername(String parametername) {
        this.parametername = parametername;
    }

    public String getParameterdesc() {
        return this.parameterdesc;
    }
    
    public void setParameterdesc(String parameterdesc) {
        this.parameterdesc = parameterdesc;
    }

    public Integer getParameterforid() {
        return this.parameterforid;
    }
    
    public void setParameterforid(Integer parameterforid) {
        this.parameterforid = parameterforid;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }
   








}
