package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TmWorkflow generated by hbm2java
 */

public class TmWorkflowHistory  implements java.io.Serializable {


    // Fields    
	private int id;	
     private int workflowid;
     private String workflowname;
     private String workflowdesc;
     private String applicationname;
     private String applicationcode;
     private int createdby;
     private Date createddate;
     private Integer modifiedby;
     private Date modifieddate;
     private int isactive;
     private TmNpdcategory npdCategory;


    // Constructors

    /** default constructor */
    public TmWorkflowHistory() {
    }

	/** minimal constructor */
    public TmWorkflowHistory(int workflowid, int createdby, Date createddate, int isactive) {
        this.workflowid = workflowid;
        this.createdby = createdby;
        this.createddate = createddate;
        this.isactive = isactive;
    }
    
    /** full constructor */
    public TmWorkflowHistory(int workflowid, String workflowname, String workflowdesc, String applicationname, String applicationcode, int createdby, Date createddate, Integer modifiedby, Date modifieddate, int isactive,TmNpdcategory npdCategory) {
        this.workflowid = workflowid;
        this.workflowname = workflowname;
        this.workflowdesc = workflowdesc;
        this.applicationname = applicationname;
        this.applicationcode = applicationcode;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
        this.isactive = isactive;
        this.npdCategory=npdCategory;
    }
    

   
    // Property accessors

    public int getWorkflowid() {
        return this.workflowid;
    }
    
    public void setWorkflowid(int workflowid) {
        this.workflowid = workflowid;
    }

    public String getWorkflowname() {
        return this.workflowname;
    }
    
    public void setWorkflowname(String workflowname) {
        this.workflowname = workflowname;
    }

    public String getWorkflowdesc() {
        return this.workflowdesc;
    }
    
    public void setWorkflowdesc(String workflowdesc) {
        this.workflowdesc = workflowdesc;
    }

    public String getApplicationname() {
        return this.applicationname;
    }
    
    public void setApplicationname(String applicationname) {
        this.applicationname = applicationname;
    }

    public String getApplicationcode() {
        return this.applicationcode;
    }
    
    public void setApplicationcode(String applicationcode) {
        this.applicationcode = applicationcode;
    }

    public int getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

	/**
	 * @return the npdCategory
	 */
	public TmNpdcategory getNpdCategory() {
		return npdCategory;
	}

	/**
	 * @param npdCategory the npdCategory to set
	 */
	public void setNpdCategory(TmNpdcategory npdCategory) {
		this.npdCategory = npdCategory;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
   








}
