package com.ibm.ioes.npd.hibernate.beans;

// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.ibm.ioes.npd.utilities.PagingSorting;
import com.ibm.ioes.npd.utilities.Utility;

/**
 * TtrnProject generated by hbm2java
 */

public class TtrnProject implements java.io.Serializable {

	// Fields

	private long projectid;

	private Integer projectstatus;

	private int createdby;

	private Date createddate;

	private Integer modifiedby;

	private Date modifieddate;

	private int isactive;

	private Set ttrnProjectriskses = new HashSet(0);

	private Set ttrnProjectplrses = new HashSet(0);

	private Set ttrnProjectisssueses = new HashSet(0);

	private Set ttrnProjectassumptionses = new HashSet(0);

	private TmNpdcategory npdCategory;

	private String projectName;

	private TmProductcategory prdCategory;

	private String airtelPotential;

	private String capexReq;

	private String targetMkt;

	private String totalMktPotential;

	private Date expectedLaunchDate;

	private String launchPriority;

	private String productBrief;

	private Date startDate;

	private Integer prdCategoryId;
	
	PagingSorting pagingSorting = null;
	
	private String searchStatus=null;
	private String searchProjectId=null;
	private String searchProjectName=null;
	private String searchProductCategoryId=null;
	private String searchNpdCategoryId=null;
	
	private String prdCategoryName=null;
	private String npdCategoryName=null;
	
	private String workflowAttachStatus=null;
	
	private long finalizedProjectWorkflowId;
	private long draftProjectWorkflowId;
	// Constructors

	private String assignedToUser = null;
	
	private String currentstatus= null;
	
	private String currentTask= null;
	
	private String rfiId= null;
	
	private String daysWithCurrentUser= null;
	
	private String stageId= null;
	
	private String taskId= null;
	
	private String productCatDesc= null;
	
	private String rfiRemarks= null;
	
	private Blob rfiDocument= null;
	
	private String productUpdationFlag=null;
	
	private String updationRequestedBy=null;
	private String updationRequestedByName=null;
	private String updationRequestedByRoleId=null;
	private String updationRequestedByRoleName=null;
	private String updationRequestedByEmail=null;
	
	private long projectworkflowid;
	
	private String projectCurrentVersion=null;
	
	private String CSV_id_name=null;
	
	private Long RoleId=null;
	
	private Long productId;
	
	
	public Long getProductId() {
		return productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public long getProjectworkflowid() {
		return projectworkflowid;
	}

	public void setProjectworkflowid(long projectworkflowid) {
		this.projectworkflowid = projectworkflowid;
	}

	/** default constructor */
	public TtrnProject() {
	}

	/** minimal constructor */
	public TtrnProject(long projectid, int createdby, Date createddate,
			int isactive, TmNpdcategory npdCategory, String projectName,
			TmProductcategory prdCategory, String airtelPotential, String capexReq,
			String targetMkt, String totalMktPotential,
			Date expectedLaunchDate, String launchPriority,
			String productBrief, Date startDate) {
		this.projectid = projectid;
		this.createdby = createdby;
		this.createddate = createddate;
		this.isactive = isactive;
		this.npdCategory = npdCategory;
		this.projectName = projectName;
		this.prdCategory = prdCategory;
		this.airtelPotential = airtelPotential;
		this.capexReq = capexReq;
		this.targetMkt = targetMkt;
		this.totalMktPotential = totalMktPotential;
		this.expectedLaunchDate = expectedLaunchDate;
		this.launchPriority = launchPriority;
		this.productBrief = productBrief;
		this.startDate = startDate;
	}

	/** full constructor */
	public TtrnProject(long projectid, Integer projectstatus, int createdby,
			Date createddate, Integer modifiedby, Date modifieddate,
			int isactive, Set ttrnProjectriskses, Set ttrnProjectplrses,
			Set ttrnProjectisssueses, Set ttrnProjectassumptionses,
			TmNpdcategory npdCategory, String projectName, TmProductcategory prdCategory,
			String airtelPotential, String capexReq, String targetMkt,
			String totalMktPotential, Date expectedLaunchDate,
			String launchPriority, String productBrief, Date startDate) {
		this.projectid = projectid;
		this.projectstatus = projectstatus;
		this.createdby = createdby;
		this.createddate = createddate;
		this.modifiedby = modifiedby;
		this.modifieddate = modifieddate;
		this.isactive = isactive;
		this.ttrnProjectriskses = ttrnProjectriskses;
		this.ttrnProjectplrses = ttrnProjectplrses;
		this.ttrnProjectisssueses = ttrnProjectisssueses;
		this.ttrnProjectassumptionses = ttrnProjectassumptionses;

		this.npdCategory = npdCategory;
		this.projectName = projectName;
		this.prdCategory = prdCategory;
		this.airtelPotential = airtelPotential;
		this.capexReq = capexReq;
		this.targetMkt = targetMkt;
		this.totalMktPotential = totalMktPotential;
		this.expectedLaunchDate = expectedLaunchDate;
		this.launchPriority = launchPriority;
		this.productBrief = productBrief;
		this.startDate = startDate;
	}

	// Property accessors

	public long getProjectid() {
		return this.projectid;
	}

	public void setProjectid(long projectid) {
		this.projectid = projectid;
	}

	public Integer getProjectstatus() {
		return this.projectstatus;
	}

	public void setProjectstatus(Integer projectstatus) {
		this.projectstatus = projectstatus;
	}

	public int getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(int createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Integer getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(Integer modifiedby) {
		this.modifiedby = modifiedby;
	}

	public Date getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	public int getIsactive() {
		return this.isactive;
	}

	public void setIsactive(int isactive) {
		this.isactive = isactive;
	}

	public Set getTtrnProjectriskses() {
		return this.ttrnProjectriskses;
	}

	public void setTtrnProjectriskses(Set ttrnProjectriskses) {
		this.ttrnProjectriskses = ttrnProjectriskses;
	}

	public Set getTtrnProjectplrses() {
		return this.ttrnProjectplrses;
	}

	public void setTtrnProjectplrses(Set ttrnProjectplrses) {
		this.ttrnProjectplrses = ttrnProjectplrses;
	}

	public Set getTtrnProjectisssueses() {
		return this.ttrnProjectisssueses;
	}

	public void setTtrnProjectisssueses(Set ttrnProjectisssueses) {
		this.ttrnProjectisssueses = ttrnProjectisssueses;
	}

	public Set getTtrnProjectassumptionses() {
		return this.ttrnProjectassumptionses;
	}

	public void setTtrnProjectassumptionses(Set ttrnProjectassumptionses) {
		this.ttrnProjectassumptionses = ttrnProjectassumptionses;
	}

	/**
	 * @return the capexReq
	 */
	public String getCapexReq() {
		return capexReq;
	}

	/**
	 * @param capexReq
	 *            the capexReq to set
	 */
	public void setCapexReq(String capexReq) {
		this.capexReq = capexReq;
	}

	

	/**
	 * @return the npdCategory
	 */
	public TmNpdcategory getNpdCategory() {
		return npdCategory;
	}

	/**
	 * @param npdCategory the npdCategory to set
	 */
	public void setNpdCategory(TmNpdcategory npdCategory) {
		this.npdCategory = npdCategory;
	}

	/**
	 * @return the prdCategory
	 */
	public TmProductcategory getPrdCategory() {
		return prdCategory;
	}

	/**
	 * @param prdCategory
	 *            the prdCategory to set
	 */
	public void setPrdCategory(TmProductcategory prdCategory) {
		this.prdCategory = prdCategory;
	}

	/**
	 * @return the projectName
	 */
	public String getProjectName() {
		return projectName;
	}
	
	public String getProjectNameShort() {
		return Utility.shortForReport(projectName, 50);
	}

	/**
	 * @param projectName
	 *            the projectName to set
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	/**
	 * @return the targetMkt
	 */
	public String getTargetMkt() {
		return targetMkt;
	}

	/**
	 * @param targetMkt
	 *            the targetMkt to set
	 */
	public void setTargetMkt(String targetMkt) {
		this.targetMkt = targetMkt;
	}

	/**
	 * @return the totalMktPotential
	 */
	public String getTotalMktPotential() {
		return totalMktPotential;
	}

	/**
	 * @param totalMktPotential
	 *            the totalMktPotential to set
	 */
	public void setTotalMktPotential(String totalMktPotential) {
		this.totalMktPotential = totalMktPotential;
	}

	/**
	 * @return the airtelPotential
	 */
	public String getAirtelPotential() {
		return airtelPotential;
	}

	/**
	 * @param airtelPotential
	 *            the airtelPotential to set
	 */
	public void setAirtelPotential(String airtelPotential) {
		this.airtelPotential = airtelPotential;
	}

	/**
	 * @return the expectedLaunchDate
	 */
	public Date getExpectedLaunchDate() {
		return expectedLaunchDate;
	}

	/**
	 * @param expectedLaunchDate
	 *            the expectedLaunchDate to set
	 */
	public void setExpectedLaunchDate(Date expectedLaunchDate) {
		this.expectedLaunchDate = expectedLaunchDate;
	}

	/**
	 * @return the launchPriority
	 */
	public String getLaunchPriority() {
		return launchPriority;
	}

	/**
	 * @param launchPriority
	 *            the launchPriority to set
	 */
	public void setLaunchPriority(String launchPriority) {
		this.launchPriority = launchPriority;
	}

	/**
	 * @return the productBrief
	 */
	public String getProductBrief() {
		return productBrief;
	}

	/**
	 * @param productBrief
	 *            the productBrief to set
	 */
	public void setProductBrief(String productBrief) {
		this.productBrief = productBrief;
	}

	/**
	 * @return the startDate
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * @param startDate
	 *            the startDate to set
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public PagingSorting getPagingSorting() {
		return pagingSorting;
	}

	public void setPagingSorting(PagingSorting pagingSorting) {
		this.pagingSorting = pagingSorting;
	}

	public String getSearchStatus() {
		return searchStatus;
	}

	public void setSearchStatus(String searchStatus) {
		this.searchStatus = searchStatus;
	}

	public String getSearchNpdCategoryId() {
		return searchNpdCategoryId;
	}

	public void setSearchNpdCategoryId(String searchNpdCategoryId) {
		this.searchNpdCategoryId = searchNpdCategoryId;
	}

	public String getSearchProductCategoryId() {
		return searchProductCategoryId;
	}

	public void setSearchProductCategoryId(String searchProductCategoryId) {
		this.searchProductCategoryId = searchProductCategoryId;
	}

	public String getSearchProjectId() {
		return searchProjectId;
	}

	public void setSearchProjectId(String searchProjectId) {
		this.searchProjectId = searchProjectId;
	}

	public String getSearchProjectName() {
		return searchProjectName;
	}

	public void setSearchProjectName(String searchProjectName) {
		this.searchProjectName = searchProjectName;
	}

	public String getNpdCategoryName() {
		return npdCategoryName;
	}

	public void setNpdCategoryName(String npdCategoryName) {
		this.npdCategoryName = npdCategoryName;
	}

	public String getPrdCategoryName() {
		return prdCategoryName;
	}

	public void setPrdCategoryName(String prdCategoryName) {
		this.prdCategoryName = prdCategoryName;
	}

	public String getWorkflowAttachStatus() {
		return workflowAttachStatus;
	}

	public void setWorkflowAttachStatus(String workflowAttachStatus) {
		this.workflowAttachStatus = workflowAttachStatus;
	}

	public long getDraftProjectWorkflowId() {
		return draftProjectWorkflowId;
	}

	public void setDraftProjectWorkflowId(long draftProjectWorkflowId) {
		this.draftProjectWorkflowId = draftProjectWorkflowId;
	}

	public long getFinalizedProjectWorkflowId() {
		return finalizedProjectWorkflowId;
	}

	public void setFinalizedProjectWorkflowId(long finalizedProjectWorkflowId) {
		this.finalizedProjectWorkflowId = finalizedProjectWorkflowId;
	}

	public String getAssignedToUser() {
		return assignedToUser;
	}

	public void setAssignedToUser(String assignedToUser) {
		this.assignedToUser = assignedToUser;
	}

	public String getCurrentstatus() {
		return currentstatus;
	}

	public void setCurrentstatus(String currentstatus) {
		this.currentstatus = currentstatus;
	}

	public String getCurrentTask() {
		return currentTask;
	}

	public void setCurrentTask(String currentTask) {
		this.currentTask = currentTask;
	}

	public String getDaysWithCurrentUser() {
		return daysWithCurrentUser;
	}

	public void setDaysWithCurrentUser(String daysWithCurrentUser) {
		this.daysWithCurrentUser = daysWithCurrentUser;
	}

	public Integer getPrdCategoryId() {
		return prdCategoryId;
	}

	public void setPrdCategoryId(Integer prdCategoryId) {
		this.prdCategoryId = prdCategoryId;
	}

	public String getProductCatDesc() {
		return productCatDesc;
	}

	public void setProductCatDesc(String productCatDesc) {
		this.productCatDesc = productCatDesc;
	}

	public Blob getRfiDocument() {
		return rfiDocument;
	}

	public void setRfiDocument(Blob rfiDocument) {
		this.rfiDocument = rfiDocument;
	}

	public String getRfiId() {
		return rfiId;
	}

	public void setRfiId(String rfiId) {
		this.rfiId = rfiId;
	}

	public String getRfiRemarks() {
		return rfiRemarks;
	}

	public void setRfiRemarks(String rfiRemarks) {
		this.rfiRemarks = rfiRemarks;
	}

	public String getStageId() {
		return stageId;
	}

	public void setStageId(String stageId) {
		this.stageId = stageId;
	}

	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public String getProductUpdationFlag() {
		return productUpdationFlag;
	}

	public void setProductUpdationFlag(String productUpdationFlag) {
		this.productUpdationFlag = productUpdationFlag;
	}

	public String getUpdationRequestedBy() {
		return updationRequestedBy;
	}

	public void setUpdationRequestedBy(String updationRequestedBy) {
		this.updationRequestedBy = updationRequestedBy;
	}

	public String getUpdationRequestedByName() {
		return updationRequestedByName;
	}

	public void setUpdationRequestedByName(String updationRequestedByName) {
		this.updationRequestedByName = updationRequestedByName;
	}

	public String getUpdationRequestedByRoleId() {
		return updationRequestedByRoleId;
	}

	public void setUpdationRequestedByRoleId(String updationRequestedByRoleId) {
		this.updationRequestedByRoleId = updationRequestedByRoleId;
	}

	public String getUpdationRequestedByRoleName() {
		return updationRequestedByRoleName;
	}

	public void setUpdationRequestedByRoleName(String updationRequestedByRoleName) {
		this.updationRequestedByRoleName = updationRequestedByRoleName;
	}

	public String getUpdationRequestedByEmail() {
		return updationRequestedByEmail;
	}

	public void setUpdationRequestedByEmail(String updationRequestedByEmail) {
		this.updationRequestedByEmail = updationRequestedByEmail;
	}

	public String getProjectCurrentVersion() {
		return projectCurrentVersion;
	}

	public void setProjectCurrentVersion(String projectCurrentVersion) {
		this.projectCurrentVersion = projectCurrentVersion;
	}

	public String getCSV_id_name() {
		return CSV_id_name;
	}

	public void setCSV_id_name(String csv_id_name) {
		CSV_id_name = csv_id_name;
	}

	public Long getRoleId() {
		return RoleId;
	}

	public void setRoleId(Long roleId) {
		RoleId = roleId;
	}
}
