package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TtrnProjectassumptions generated by hbm2java
 */

public class TtrnProjectassumptions  implements java.io.Serializable {


    // Fields    

     private long projassumid;
     private TtrnProject ttrnProject;
     private String description;
     private String impact;
     private Date raiseddate;
     private int isactive;
     private long createdby;
     private Date createddate;
     private Long modifiedby;
     private Date modifieddate;


    // Constructors

    /** default constructor */
    public TtrnProjectassumptions() {
    }

	/** minimal constructor */
    public TtrnProjectassumptions(long projassumid, TtrnProject ttrnProject, String description, Date raiseddate, int isactive, long createdby, Date createddate) {
        this.projassumid = projassumid;
        this.ttrnProject = ttrnProject;
        this.description = description;
        this.raiseddate = raiseddate;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
    }
    
    /** full constructor */
    public TtrnProjectassumptions(long projassumid, TtrnProject ttrnProject, String description, String impact, Date raiseddate, int isactive, long createdby, Date createddate, Long modifiedby, Date modifieddate) {
        this.projassumid = projassumid;
        this.ttrnProject = ttrnProject;
        this.description = description;
        this.impact = impact;
        this.raiseddate = raiseddate;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
    }
    

   
    // Property accessors

    public long getProjassumid() {
        return this.projassumid;
    }
    
    public void setProjassumid(long projassumid) {
        this.projassumid = projassumid;
    }

    public TtrnProject getTtrnProject() {
        return this.ttrnProject;
    }
    
    public void setTtrnProject(TtrnProject ttrnProject) {
        this.ttrnProject = ttrnProject;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getImpact() {
        return this.impact;
    }
    
    public void setImpact(String impact) {
        this.impact = impact;
    }

    public Date getRaiseddate() {
        return this.raiseddate;
    }
    
    public void setRaiseddate(Date raiseddate) {
        this.raiseddate = raiseddate;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
}
