package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.sql.Blob;
import java.util.Date;


/**
 * TtrnProjectplrdetails generated by hbm2java
 */

public class TtrnProjectplrdetails  implements java.io.Serializable {


    // Fields    

     private long projplrdetid;
     private TtrnProjectplrs ttrnProjectplrs;
     private long npdempid;
     private int issubmitted;
     private Blob plrattachment;
     private int isactive;
     private long createdby;
     private Date createddate;
     private Long modifiedby;
     private Date modifieddate;


    // Constructors

    /** default constructor */
    public TtrnProjectplrdetails() {
    }

	/** minimal constructor */
    public TtrnProjectplrdetails(long projplrdetid, TtrnProjectplrs ttrnProjectplrs, long npdempid, int issubmitted, int isactive, long createdby, Date createddate) {
        this.projplrdetid = projplrdetid;
        this.ttrnProjectplrs = ttrnProjectplrs;
        this.npdempid = npdempid;
        this.issubmitted = issubmitted;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
    }
    
    /** full constructor */
    public TtrnProjectplrdetails(long projplrdetid, TtrnProjectplrs ttrnProjectplrs, long npdempid, int issubmitted, Blob plrattachment, int isactive, long createdby, Date createddate, Long modifiedby, Date modifieddate) {
        this.projplrdetid = projplrdetid;
        this.ttrnProjectplrs = ttrnProjectplrs;
        this.npdempid = npdempid;
        this.issubmitted = issubmitted;
        this.plrattachment = plrattachment;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
    }
    

   
    // Property accessors

    public long getProjplrdetid() {
        return this.projplrdetid;
    }
    
    public void setProjplrdetid(long projplrdetid) {
        this.projplrdetid = projplrdetid;
    }

    public TtrnProjectplrs getTtrnProjectplrs() {
        return this.ttrnProjectplrs;
    }
    
    public void setTtrnProjectplrs(TtrnProjectplrs ttrnProjectplrs) {
        this.ttrnProjectplrs = ttrnProjectplrs;
    }

    public long getNpdempid() {
        return this.npdempid;
    }
    
    public void setNpdempid(long npdempid) {
        this.npdempid = npdempid;
    }

    public int getIssubmitted() {
        return this.issubmitted;
    }
    
    public void setIssubmitted(int issubmitted) {
        this.issubmitted = issubmitted;
    }

    public Blob getPlrattachment() {
        return this.plrattachment;
    }
    
    public void setPlrattachment(Blob plrattachment) {
        this.plrattachment = plrattachment;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
   








}
