package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4



/**
 * TtrnProjectactiondocs generated by hbm2java
 */

public class TtrnProjectactiondocs  implements java.io.Serializable {


    // Fields    

     private TtrnProjectactiondocsId id;


    // Constructors

    /** default constructor */
    public TtrnProjectactiondocs() {
    }

    
    /** full constructor */
    public TtrnProjectactiondocs(TtrnProjectactiondocsId id) {
        this.id = id;
    }
    

   
    // Property accessors

    public TtrnProjectactiondocsId getId() {
        return this.id;
    }
    
    public void setId(TtrnProjectactiondocsId id) {
        this.id = id;
    }
   








}
