package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:38 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TtrnProjectrisks generated by hbm2java
 */

public class TtrnProjectrisks  implements java.io.Serializable {


    // Fields    

     private long projriskid;
     private TtrnProject ttrnProject;
     private String description;
     private int status;
     private String risksource;
     private String priority;
     private Integer level;
     private Integer resolutiontime;
     private TmEmployee raisedby;
     private Date raiseddate;
     private TmEmployee migratedowner;
     private TmEmployee riskowner;
     private Date plannedresodate;
     private Date actualresodate;
     private String probability;
     private String impact;
     private String mitigationplan;
     private String riskimpact;
     private int isactive;
     private TmEmployee createdby;
     private Date createddate;
     private TmEmployee modifiedby;
     private Date modifieddate;


    // Constructors

    /** default constructor */
    public TtrnProjectrisks() {
    }

	/** minimal constructor */
    public TtrnProjectrisks(long projriskid, TtrnProject ttrnProject, String description, int status, String priority, TmEmployee raisedby, Date raiseddate, String probability, String impact, int isactive, TmEmployee createdby, Date createddate) {
        this.projriskid = projriskid;
        this.ttrnProject = ttrnProject;
        this.description = description;
        this.status = status;
        this.priority = priority;
        this.raisedby = raisedby;
        this.raiseddate = raiseddate;
        this.probability = probability;
        this.impact = impact;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
    }
    
    /** full constructor */
    public TtrnProjectrisks(long projriskid, TtrnProject ttrnProject, String description, int status, String risksource, String priority, Integer level, Integer resolutiontime, TmEmployee raisedby, Date raiseddate, TmEmployee migratedowner, TmEmployee riskowner, Date plannedresodate, Date actualresodate, String probability, String impact, String mitigationplan, String riskimpact, int isactive, TmEmployee createdby, Date createddate, TmEmployee modifiedby, Date modifieddate) {
        this.projriskid = projriskid;
        this.ttrnProject = ttrnProject;
        this.description = description;
        this.status = status;
        this.risksource = risksource;
        this.priority = priority;
        this.level = level;
        this.resolutiontime = resolutiontime;
        this.raisedby = raisedby;
        this.raiseddate = raiseddate;
        this.migratedowner = migratedowner;
        this.riskowner = riskowner;
        this.plannedresodate = plannedresodate;
        this.actualresodate = actualresodate;
        this.probability = probability;
        this.impact = impact;
        this.mitigationplan = mitigationplan;
        this.riskimpact = riskimpact;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
    }
    

   
    // Property accessors

    public long getProjriskid() {
        return this.projriskid;
    }
    
    public void setProjriskid(long projriskid) {
        this.projriskid = projriskid;
    }

    public TtrnProject getTtrnProject() {
        return this.ttrnProject;
    }
    
    public void setTtrnProject(TtrnProject ttrnProject) {
        this.ttrnProject = ttrnProject;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    public String getRisksource() {
        return this.risksource;
    }
    
    public void setRisksource(String risksource) {
        this.risksource = risksource;
    }

    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getResolutiontime() {
        return this.resolutiontime;
    }
    
    public void setResolutiontime(Integer resolutiontime) {
        this.resolutiontime = resolutiontime;
    }

 
    public TmEmployee getRaisedby() {
		return raisedby;
	}

	public void setRaisedby(TmEmployee raisedby) {
		this.raisedby = raisedby;
	}

	public Date getRaiseddate() {
        return this.raiseddate;
    }
    
    public void setRaiseddate(Date raiseddate) {
        this.raiseddate = raiseddate;
    }

    public TmEmployee getMigratedowner() {
		return migratedowner;
	}

	public void setMigratedowner(TmEmployee migratedowner) {
		this.migratedowner = migratedowner;
	}

	public TmEmployee getRiskowner() {
		return riskowner;
	}

	public void setRiskowner(TmEmployee riskowner) {
		this.riskowner = riskowner;
	}

	public Date getPlannedresodate() {
        return this.plannedresodate;
    }
    
    public void setPlannedresodate(Date plannedresodate) {
        this.plannedresodate = plannedresodate;
    }

    public Date getActualresodate() {
        return this.actualresodate;
    }
    
    public void setActualresodate(Date actualresodate) {
        this.actualresodate = actualresodate;
    }

    public String getProbability() {
        return this.probability;
    }
    
    public void setProbability(String probability) {
        this.probability = probability;
    }

    public String getImpact() {
        return this.impact;
    }
    
    public void setImpact(String impact) {
        this.impact = impact;
    }

    public String getMitigationplan() {
        return this.mitigationplan;
    }
    
    public void setMitigationplan(String mitigationplan) {
        this.mitigationplan = mitigationplan;
    }

    public String getRiskimpact() {
        return this.riskimpact;
    }
    
    public void setRiskimpact(String riskimpact) {
        this.riskimpact = riskimpact;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

   
    public TmEmployee getCreatedby() {
		return createdby;
	}

	public void setCreatedby(TmEmployee createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public TmEmployee getModifiedby() {
		return modifiedby;
	}

	public void setModifiedby(TmEmployee modifiedby) {
		this.modifiedby = modifiedby;
	}

	public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
   








}
