package com.ibm.ioes.npd.hibernate.beans;
// Generated Feb 8, 2010 10:30:27 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TtrnProjectworkflow generated by hbm2java
 */

public class TtrnProjectworkflow  implements java.io.Serializable {


    // Fields    

     private long projectworkflowid;
     private Integer projectworkflowstatus;// no use
     private int createdby;
     private Date createddate;
     private Integer modifiedby;
     private Date modifieddate;
     private int isactive;
     private String attachHistoryStatus; //workflow is completely new or an existing one is modified "editingFinalized","attachNew"
     private String workflowStatus; //"DRAFT","HISTORY","FINALIZED"

    // Constructors

    /** default constructor */
    public TtrnProjectworkflow() {
    }

	/** minimal constructor */
    public TtrnProjectworkflow(long projectworkflowid, int createdby, Date createddate, int isactive) {
        this.projectworkflowid = projectworkflowid;
        this.createdby = createdby;
        this.createddate = createddate;
        this.isactive = isactive;
    }
    
    /** full constructor */
    public TtrnProjectworkflow(long projectworkflowid, Integer projectworkflowstatus, int createdby, Date createddate, Integer modifiedby, Date modifieddate, int isactive) {
        this.projectworkflowid = projectworkflowid;
        this.projectworkflowstatus = projectworkflowstatus;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
        this.isactive = isactive;
    }
    

   
    // Property accessors

    public long getProjectworkflowid() {
        return this.projectworkflowid;
    }
    
    public void setProjectworkflowid(long projectworkflowid) {
        this.projectworkflowid = projectworkflowid;
    }

    public Integer getProjectworkflowstatus() {
        return this.projectworkflowstatus;
    }
    
    public void setProjectworkflowstatus(Integer projectworkflowstatus) {
        this.projectworkflowstatus = projectworkflowstatus;
    }

    public int getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

	public String getAttachHistoryStatus() {
		return attachHistoryStatus;
	}

	public void setAttachHistoryStatus(String attachHistoryStatus) {
		this.attachHistoryStatus = attachHistoryStatus;
	}

	public String getWorkflowStatus() {
		return workflowStatus;
	}

	public void setWorkflowStatus(String workflowStatus) {
		this.workflowStatus = workflowStatus;
	}
   








}
