package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TtrnMeetingattendies generated by hbm2java
 */

public class TtrnMeetingattendies  implements java.io.Serializable {


    // Fields    

     private long meetingattenid;
     private TtrnMeetingschedules ttrnMeetingschedules;
     private long npdempid;
     private String attentype;
     private int isactive;
     private long createdby;
     private Date createddate;
     private Long modifiedby;
     private Date modifieddate;

   	 private TmEmployee employee=new TmEmployee();;

    // Constructors

    /** default constructor */
    public TtrnMeetingattendies() {
    }

	/** minimal constructor */
    public TtrnMeetingattendies(long meetingattenid, TtrnMeetingschedules ttrnMeetingschedules, long npdempid, String attentype, int isactive, long createdby, Date createddate) {
        this.meetingattenid = meetingattenid;
        this.ttrnMeetingschedules = ttrnMeetingschedules;
        this.npdempid = npdempid;
        this.attentype = attentype;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
    }
    
    /** full constructor */
    public TtrnMeetingattendies(long meetingattenid, TtrnMeetingschedules ttrnMeetingschedules, long npdempid, String attentype, int isactive, long createdby, Date createddate, Long modifiedby, Date modifieddate) {
        this.meetingattenid = meetingattenid;
        this.ttrnMeetingschedules = ttrnMeetingschedules;
        this.npdempid = npdempid;
        this.attentype = attentype;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
    }
    

   
    // Property accessors

    public long getMeetingattenid() {
        return this.meetingattenid;
    }
    
    public void setMeetingattenid(long meetingattenid) {
        this.meetingattenid = meetingattenid;
    }

    public TtrnMeetingschedules getTtrnMeetingschedules() {
        return this.ttrnMeetingschedules;
    }
    
    public void setTtrnMeetingschedules(TtrnMeetingschedules ttrnMeetingschedules) {
        this.ttrnMeetingschedules = ttrnMeetingschedules;
    }

    public long getNpdempid() {
        return this.npdempid;
    }
    
    public void setNpdempid(long npdempid) {
        this.npdempid = npdempid;
    }

    public String getAttentype() {
        return this.attentype;
    }
    
    public void setAttentype(String attentype) {
        this.attentype = attentype;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

	public TmEmployee getEmployee() {
		return employee;
	}

	public void setEmployee(TmEmployee employee) {
		this.employee = employee;
	}
   








}
