package com.ibm.ioes.npd.hibernate.beans;

// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.sql.Blob;
import java.util.Date;

/**
 * TtrnMeetingmoms generated by hbm2java
 */

public class TtrnMeetingmoms implements java.io.Serializable {

	// Fields

	private long meetingmomid;

	private TtrnMeetingschedules tmMeetings;

	private Blob mom;

	private int isactive;

	private TmEmployee createdby;

	private Date createddate;

	private Long modifiedby;

	private Date modifieddate;

	private String filename;

	// Constructors

	/**
	 * @return the filename
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * @param filename
	 *            the filename to set
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	/** default constructor */
	public TtrnMeetingmoms() {
	}

	/** minimal constructor */
	public TtrnMeetingmoms(long meetingmomid, TtrnMeetingschedules tmMeetings,
			int isactive, TmEmployee createdby, Date createddate) {
		this.meetingmomid = meetingmomid;
		this.tmMeetings = tmMeetings;
		this.isactive = isactive;
		this.createdby = createdby;
		this.createddate = createddate;
	}

	/** full constructor */
	public TtrnMeetingmoms(long meetingmomid, TtrnMeetingschedules tmMeetings,
			Blob mom, int isactive, TmEmployee createdby, Date createddate,
			Long modifiedby, Date modifieddate, String filename) {
		this.meetingmomid = meetingmomid;
		this.tmMeetings = tmMeetings;
		this.mom = mom;
		this.isactive = isactive;
		this.createdby = createdby;
		this.createddate = createddate;
		this.modifiedby = modifiedby;
		this.modifieddate = modifieddate;
		this.filename = filename;
	}

	// Property accessors

	public long getMeetingmomid() {
		return this.meetingmomid;
	}

	public void setMeetingmomid(long meetingmomid) {
		this.meetingmomid = meetingmomid;
	}

	/**
	 * @return the tmMeetings
	 */
	public TtrnMeetingschedules getTmMeetings() {
		return tmMeetings;
	}

	/**
	 * @param tmMeetings
	 *            the tmMeetings to set
	 */
	public void setTmMeetings(TtrnMeetingschedules tmMeetings) {
		this.tmMeetings = tmMeetings;
	}

	public Blob getMom() {
		return this.mom;
	}

	public void setMom(Blob mom) {
		this.mom = mom;
	}

	public int getIsactive() {
		return this.isactive;
	}

	public void setIsactive(int isactive) {
		this.isactive = isactive;
	}


	/**
	 * @return the createdby
	 */
	public TmEmployee getCreatedby() {
		return createdby;
	}

	/**
	 * @param createdby the createdby to set
	 */
	public void setCreatedby(TmEmployee createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Long getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(Long modifiedby) {
		this.modifiedby = modifiedby;
	}

	public Date getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

}
