package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * TtrnProjectactiondetails generated by hbm2java
 */

public class TtrnProjectactiondetails  implements java.io.Serializable {


    // Fields    

     private long projectactionid;
     private long projectid;
     private Integer stageid;
     private Long taskid;
     private String taskactiontaken;
     private Integer taskowner;
     private Date actiondate;
     private String actionremarks;
     private Integer isdocsattached;
     private Integer actiontype;
     private Integer nextstageid;
     private Long nexttaskid;
     private int createdby;
     private Date createddate;
     private Integer modifiedby;
     private Date modifieddate;
     private int isactive;


    // Constructors

    /** default constructor */
    public TtrnProjectactiondetails() {
    }

	/** minimal constructor */
    public TtrnProjectactiondetails(long projectactionid, long projectid, int createdby, Date createddate, int isactive) {
        this.projectactionid = projectactionid;
        this.projectid = projectid;
        this.createdby = createdby;
        this.createddate = createddate;
        this.isactive = isactive;
    }
    
    /** full constructor */
    public TtrnProjectactiondetails(long projectactionid, long projectid, Integer stageid, Long taskid, String taskactiontaken, Integer taskowner, Date actiondate, String actionremarks, Integer isdocsattached, Integer actiontype, Integer nextstageid, Long nexttaskid, int createdby, Date createddate, Integer modifiedby, Date modifieddate, int isactive) {
        this.projectactionid = projectactionid;
        this.projectid = projectid;
        this.stageid = stageid;
        this.taskid = taskid;
        this.taskactiontaken = taskactiontaken;
        this.taskowner = taskowner;
        this.actiondate = actiondate;
        this.actionremarks = actionremarks;
        this.isdocsattached = isdocsattached;
        this.actiontype = actiontype;
        this.nextstageid = nextstageid;
        this.nexttaskid = nexttaskid;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
        this.isactive = isactive;
    }
    

   
    // Property accessors

    public long getProjectactionid() {
        return this.projectactionid;
    }
    
    public void setProjectactionid(long projectactionid) {
        this.projectactionid = projectactionid;
    }

    public long getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(long projectid) {
        this.projectid = projectid;
    }

    public Integer getStageid() {
        return this.stageid;
    }
    
    public void setStageid(Integer stageid) {
        this.stageid = stageid;
    }

    public Long getTaskid() {
        return this.taskid;
    }
    
    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }

    public String getTaskactiontaken() {
        return this.taskactiontaken;
    }
    
    public void setTaskactiontaken(String taskactiontaken) {
        this.taskactiontaken = taskactiontaken;
    }

    public Integer getTaskowner() {
        return this.taskowner;
    }
    
    public void setTaskowner(Integer taskowner) {
        this.taskowner = taskowner;
    }

    public Date getActiondate() {
        return this.actiondate;
    }
    
    public void setActiondate(Date actiondate) {
        this.actiondate = actiondate;
    }

    public String getActionremarks() {
        return this.actionremarks;
    }
    
    public void setActionremarks(String actionremarks) {
        this.actionremarks = actionremarks;
    }

    public Integer getIsdocsattached() {
        return this.isdocsattached;
    }
    
    public void setIsdocsattached(Integer isdocsattached) {
        this.isdocsattached = isdocsattached;
    }

    public Integer getActiontype() {
        return this.actiontype;
    }
    
    public void setActiontype(Integer actiontype) {
        this.actiontype = actiontype;
    }

    public Integer getNextstageid() {
        return this.nextstageid;
    }
    
    public void setNextstageid(Integer nextstageid) {
        this.nextstageid = nextstageid;
    }

    public Long getNexttaskid() {
        return this.nexttaskid;
    }
    
    public void setNexttaskid(Long nexttaskid) {
        this.nexttaskid = nexttaskid;
    }

    public int getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }
   








}
