package com.ibm.ioes.npd.hibernate.beans;
// Generated Feb 8, 2010 10:30:27 AM by Hibernate Tools 3.1.0.beta4

import java.util.ArrayList;
import java.util.Date;


/**
 * TtrnProjecthierarchy generated by hbm2java
 */

public class TtrnProjecthierarchy  implements java.io.Serializable ,Comparable<TtrnProjecthierarchy>{


    // Fields    

     private long projecthierarchyid;
     private long projectid;
     private long projectworkflowid;
     private Long workflowid;
     private Long currentstageid;
     private Long currenttaskid;
     private Long prevstageid;
     private Long prevtaskid;
     private Integer isfirsttask;
     private Integer islasttask;
     private Date stagestartdate;
     private Date stageenddate;
     private Date taskstartdate;
     private Date taskenddate;
     private Date actualstagestartdate;
     private Date actualtaskenddate;
     private Date actualtaskstartdate;
     private Date actualstageenddate;
     private Long taskduration;
     private Long stageduration;
     private Long hierarchyversion;
     private Long taskstatus;
     private Long taskstakeholder;
     private Long taskdelegatedstakeholder;
     private Long currenttaskstakeholdrole;
     private Long taskdelegatedrole;
     private Long nexttaskholderrole;
     private String taskname;
     private String taskdesc;
     private Integer taskPlanneddurationdays;
     private String taskTaskinstructionremarks;
     private Integer taskIsattachment;
     private Integer taskCreatedby;
     private Date taskCreateddate;
     private Integer taskModifiedby;
     private Date taskModifieddate;
     private Integer taskReferencedocid;
     private Integer taskTaskpriority;
     private Integer taskIsemailtemplate;
     private Integer taskIsreminderrequired;
     private Integer taskTasktype;
     private Integer rejectionAllowed;
     private Integer taskIstaskdelegable;
     private String stagename;
     private String stagedesc;
     private Integer stageCreatedby;
     private Date stageCreateddate;
     private Integer stageModifiedby;
     private Date stageModifieddate;
     private Long assignedtouserid;
     private Long createdby;
     private Date createddate;
     private Integer isactive;

     ArrayList<TmstProjecthierarchytasksflow> PrevTaskList=null;
     ArrayList<TmstProjecthierarchytasksflow> NextTaskList=null;
     
     ArrayList<TmEmployee> assignedUserList=null;
     
     private String taskstakeholderName;
     private String assignedtouserName;
     private String taskReferencedocname;
     
     private String CSV_nextTasksName;
     
     String currentTaskStatus=null;
     
     ArrayList<TtrnProjecthierarchy> validPrevTaskList=null;
     String[] selectedPrevTaskIds = null;
     
     private ArrayList curPrevTasks=null;
	 
	 String errorLog=null;
 
     /*
      * getPrevTaskIds() retrieves from  ArrayList<TmstProjecthierarchytasksflow> PrevTaskList defined above
      */
	public Long[] getPrevTaskIds()
     {
    	 if(PrevTaskList==null)
    	 {
    		 return new Long[0];
    	 }
    	 Long[] prevTaskIds=new Long[PrevTaskList.size()];
    	 int i=0;
    	 for (TmstProjecthierarchytasksflow prev : PrevTaskList) {
    		 prevTaskIds[i++]=prev.getPrevtaskid();
    	 }
    	 return prevTaskIds;
     }
    // Constructors

    /** default constructor */
    public TtrnProjecthierarchy() {
    }

	/** minimal constructor */
    public TtrnProjecthierarchy(long projecthierarchyid, long projectid) {
        this.projecthierarchyid = projecthierarchyid;
        this.projectid = projectid;
    }
    
    /** full constructor */
    public TtrnProjecthierarchy(long projecthierarchyid, long projectid, Long workflowid, Long currentstageid, Long currenttaskid, Long prevstageid, Long prevtaskid, Integer isfirsttask, Integer islasttask, Date stagestartdate, Date stageenddate, Date taskstartdate, Date taskenddate, Date actualstagestartdate, Date actualtaskenddate, Date actualtaskstartdate, Date actualstageenddate, Long taskduration, Long stageduration, Long hierarchyversion, Long taskstatus, Long taskstakeholder, Long taskdelegatedstakeholder, Long currenttaskstakeholdrole, Long taskdelegatedrole, Long nexttaskholderrole, String taskname, String taskdesc, Integer taskPlanneddurationdays, String taskTaskinstructionremarks, Integer taskIsattachment, Integer taskCreatedby, Date taskCreateddate, Integer taskModifiedby, Date taskModifieddate, Integer taskReferencedocid, Integer taskTaskpriority, Integer taskIsemailtemplate, Integer taskIsreminderrequired, Integer taskTasktype, Integer taskIstaskdelegable, String stagename, String stagedesc, Integer stageCreatedby, Date stageCreateddate, Integer stageModifiedby, Date stageModifieddate, Long assignedtouserid, Long createdby, Date createddate, Integer isactive) {
        this.projecthierarchyid = projecthierarchyid;
        this.projectid = projectid;
        this.workflowid = workflowid;
        this.currentstageid = currentstageid;
        this.currenttaskid = currenttaskid;
        this.prevstageid = prevstageid;
        this.prevtaskid = prevtaskid;
        this.isfirsttask = isfirsttask;
        this.islasttask = islasttask;
        this.stagestartdate = stagestartdate;
        this.stageenddate = stageenddate;
        this.taskstartdate = taskstartdate;
        this.taskenddate = taskenddate;
        this.actualstagestartdate = actualstagestartdate;
        this.actualtaskenddate = actualtaskenddate;
        this.actualtaskstartdate = actualtaskstartdate;
        this.actualstageenddate = actualstageenddate;
        this.taskduration = taskduration;
        this.stageduration = stageduration;
        this.hierarchyversion = hierarchyversion;
        this.taskstatus = taskstatus;
        this.taskstakeholder = taskstakeholder;
        this.taskdelegatedstakeholder = taskdelegatedstakeholder;
        this.currenttaskstakeholdrole = currenttaskstakeholdrole;
        this.taskdelegatedrole = taskdelegatedrole;
        this.nexttaskholderrole = nexttaskholderrole;
        this.taskname = taskname;
        this.taskdesc = taskdesc;
        this.taskPlanneddurationdays = taskPlanneddurationdays;
        this.taskTaskinstructionremarks = taskTaskinstructionremarks;
        this.taskIsattachment = taskIsattachment;
        this.taskCreatedby = taskCreatedby;
        this.taskCreateddate = taskCreateddate;
        this.taskModifiedby = taskModifiedby;
        this.taskModifieddate = taskModifieddate;
        this.taskReferencedocid = taskReferencedocid;
        this.taskTaskpriority = taskTaskpriority;
        this.taskIsemailtemplate = taskIsemailtemplate;
        this.taskIsreminderrequired = taskIsreminderrequired;
        this.taskTasktype = taskTasktype;
        this.taskIstaskdelegable = taskIstaskdelegable;
        this.stagename = stagename;
        this.stagedesc = stagedesc;
        this.stageCreatedby = stageCreatedby;
        this.stageCreateddate = stageCreateddate;
        this.stageModifiedby = stageModifiedby;
        this.stageModifieddate = stageModifieddate;
        this.assignedtouserid = assignedtouserid;
        this.createdby = createdby;
        this.createddate = createddate;
        this.isactive = isactive;
    }
    

   
    // Property accessors

    public long getProjecthierarchyid() {
        return this.projecthierarchyid;
    }
    
    public void setProjecthierarchyid(long projecthierarchyid) {
        this.projecthierarchyid = projecthierarchyid;
    }

    public long getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(long projectid) {
        this.projectid = projectid;
    }

    public Long getWorkflowid() {
        return this.workflowid;
    }
    
    public void setWorkflowid(Long workflowid) {
        this.workflowid = workflowid;
    }

    public Long getCurrentstageid() {
        return this.currentstageid;
    }
    
    public void setCurrentstageid(Long currentstageid) {
        this.currentstageid = currentstageid;
    }

    public Long getCurrenttaskid() {
        return this.currenttaskid;
    }
    
    public void setCurrenttaskid(Long currenttaskid) {
        this.currenttaskid = currenttaskid;
    }

    public Long getPrevstageid() {
        return this.prevstageid;
    }
    
    public void setPrevstageid(Long prevstageid) {
        this.prevstageid = prevstageid;
    }

    public Long getPrevtaskid() {
        return this.prevtaskid;
    }
    
    public void setPrevtaskid(Long prevtaskid) {
        this.prevtaskid = prevtaskid;
    }

    public Integer getIsfirsttask() {
        return this.isfirsttask;
    }
    
    public void setIsfirsttask(Integer isfirsttask) {
        this.isfirsttask = isfirsttask;
    }

    public Integer getIslasttask() {
        return this.islasttask;
    }
    
    public void setIslasttask(Integer islasttask) {
        this.islasttask = islasttask;
    }

    public Date getStagestartdate() {
        return this.stagestartdate;
    }
    
    public void setStagestartdate(Date stagestartdate) {
        this.stagestartdate = stagestartdate;
    }

    public Date getStageenddate() {
        return this.stageenddate;
    }
    
    public void setStageenddate(Date stageenddate) {
        this.stageenddate = stageenddate;
    }

    public Date getTaskstartdate() {
        return this.taskstartdate;
    }
    
    public void setTaskstartdate(Date taskstartdate) {
        this.taskstartdate = taskstartdate;
    }

    public Date getTaskenddate() {
        return this.taskenddate;
    }
    
    public void setTaskenddate(Date taskenddate) {
        this.taskenddate = taskenddate;
    }

    public Date getActualstagestartdate() {
        return this.actualstagestartdate;
    }
    
    public void setActualstagestartdate(Date actualstagestartdate) {
        this.actualstagestartdate = actualstagestartdate;
    }

    public Date getActualtaskenddate() {
        return this.actualtaskenddate;
    }
    
    public void setActualtaskenddate(Date actualtaskenddate) {
        this.actualtaskenddate = actualtaskenddate;
    }

    public Date getActualtaskstartdate() {
        return this.actualtaskstartdate;
    }
    
    public void setActualtaskstartdate(Date actualtaskstartdate) {
        this.actualtaskstartdate = actualtaskstartdate;
    }

    public Date getActualstageenddate() {
        return this.actualstageenddate;
    }
    
    public void setActualstageenddate(Date actualstageenddate) {
        this.actualstageenddate = actualstageenddate;
    }

    public Long getTaskduration() {
        return this.taskduration;
    }
    
    public void setTaskduration(Long taskduration) {
        this.taskduration = taskduration;
    }

    public Long getStageduration() {
        return this.stageduration;
    }
    
    public void setStageduration(Long stageduration) {
        this.stageduration = stageduration;
    }

    public Long getHierarchyversion() {
        return this.hierarchyversion;
    }
    
    public void setHierarchyversion(Long hierarchyversion) {
        this.hierarchyversion = hierarchyversion;
    }

    public Long getTaskstatus() {
        return this.taskstatus;
    }
    
    public void setTaskstatus(Long taskstatus) {
        this.taskstatus = taskstatus;
    }

    public Long getTaskstakeholder() {
        return this.taskstakeholder;
    }
    
    public void setTaskstakeholder(Long taskstakeholder) {
        this.taskstakeholder = taskstakeholder;
    }

    public Long getTaskdelegatedstakeholder() {
        return this.taskdelegatedstakeholder;
    }
    
    public void setTaskdelegatedstakeholder(Long taskdelegatedstakeholder) {
        this.taskdelegatedstakeholder = taskdelegatedstakeholder;
    }

    public Long getCurrenttaskstakeholdrole() {
        return this.currenttaskstakeholdrole;
    }
    
    public void setCurrenttaskstakeholdrole(Long currenttaskstakeholdrole) {
        this.currenttaskstakeholdrole = currenttaskstakeholdrole;
    }

    public Long getTaskdelegatedrole() {
        return this.taskdelegatedrole;
    }
    
    public void setTaskdelegatedrole(Long taskdelegatedrole) {
        this.taskdelegatedrole = taskdelegatedrole;
    }

    public Long getNexttaskholderrole() {
        return this.nexttaskholderrole;
    }
    
    public void setNexttaskholderrole(Long nexttaskholderrole) {
        this.nexttaskholderrole = nexttaskholderrole;
    }

    public String getTaskname() {
        return this.taskname;
    }
    
    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    public String getTaskdesc() {
        return this.taskdesc;
    }
    
    public void setTaskdesc(String taskdesc) {
        this.taskdesc = taskdesc;
    }

    public Integer getTaskPlanneddurationdays() {
        return this.taskPlanneddurationdays;
    }
    
    public void setTaskPlanneddurationdays(Integer taskPlanneddurationdays) {
        this.taskPlanneddurationdays = taskPlanneddurationdays;
    }

    public String getTaskTaskinstructionremarks() {
        return this.taskTaskinstructionremarks;
    }
    
    public void setTaskTaskinstructionremarks(String taskTaskinstructionremarks) {
        this.taskTaskinstructionremarks = taskTaskinstructionremarks;
    }

    public Integer getTaskIsattachment() {
        return this.taskIsattachment;
    }
    
    public void setTaskIsattachment(Integer taskIsattachment) {
        this.taskIsattachment = taskIsattachment;
    }

    public Integer getTaskCreatedby() {
        return this.taskCreatedby;
    }
    
    public void setTaskCreatedby(Integer taskCreatedby) {
        this.taskCreatedby = taskCreatedby;
    }

    public Date getTaskCreateddate() {
        return this.taskCreateddate;
    }
    
    public void setTaskCreateddate(Date taskCreateddate) {
        this.taskCreateddate = taskCreateddate;
    }

    public Integer getTaskModifiedby() {
        return this.taskModifiedby;
    }
    
    public void setTaskModifiedby(Integer taskModifiedby) {
        this.taskModifiedby = taskModifiedby;
    }

    public Date getTaskModifieddate() {
        return this.taskModifieddate;
    }
    
    public void setTaskModifieddate(Date taskModifieddate) {
        this.taskModifieddate = taskModifieddate;
    }

    public Integer getTaskReferencedocid() {
        return this.taskReferencedocid;
    }
    
    public void setTaskReferencedocid(Integer taskReferencedocid) {
        this.taskReferencedocid = taskReferencedocid;
    }

    public Integer getTaskTaskpriority() {
        return this.taskTaskpriority;
    }
    
    public void setTaskTaskpriority(Integer taskTaskpriority) {
        this.taskTaskpriority = taskTaskpriority;
    }

    public Integer getTaskIsemailtemplate() {
        return this.taskIsemailtemplate;
    }
    
    public void setTaskIsemailtemplate(Integer taskIsemailtemplate) {
        this.taskIsemailtemplate = taskIsemailtemplate;
    }

    public Integer getTaskIsreminderrequired() {
        return this.taskIsreminderrequired;
    }
    
    public void setTaskIsreminderrequired(Integer taskIsreminderrequired) {
        this.taskIsreminderrequired = taskIsreminderrequired;
    }

    public Integer getTaskTasktype() {
        return this.taskTasktype;
    }
    
    public void setTaskTasktype(Integer taskTasktype) {
        this.taskTasktype = taskTasktype;
    }

    public Integer getTaskIstaskdelegable() {
        return this.taskIstaskdelegable;
    }
    
    public void setTaskIstaskdelegable(Integer taskIstaskdelegable) {
        this.taskIstaskdelegable = taskIstaskdelegable;
    }

    public String getStagename() {
        return this.stagename;
    }
    
    public void setStagename(String stagename) {
        this.stagename = stagename;
    }

    public String getStagedesc() {
        return this.stagedesc;
    }
    
    public void setStagedesc(String stagedesc) {
        this.stagedesc = stagedesc;
    }

    public Integer getStageCreatedby() {
        return this.stageCreatedby;
    }
    
    public void setStageCreatedby(Integer stageCreatedby) {
        this.stageCreatedby = stageCreatedby;
    }

    public Date getStageCreateddate() {
        return this.stageCreateddate;
    }
    
    public void setStageCreateddate(Date stageCreateddate) {
        this.stageCreateddate = stageCreateddate;
    }

    public Integer getStageModifiedby() {
        return this.stageModifiedby;
    }
    
    public void setStageModifiedby(Integer stageModifiedby) {
        this.stageModifiedby = stageModifiedby;
    }

    public Date getStageModifieddate() {
        return this.stageModifieddate;
    }
    
    public void setStageModifieddate(Date stageModifieddate) {
        this.stageModifieddate = stageModifieddate;
    }

    public Long getAssignedtouserid() {
        return this.assignedtouserid;
    }
    
    public void setAssignedtouserid(Long assignedtouserid) {
        this.assignedtouserid = assignedtouserid;
    }

    public Long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Integer getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

	public long getProjectworkflowid() {
		return projectworkflowid;
	}

	public void setProjectworkflowid(long projectworkflowid) {
		this.projectworkflowid = projectworkflowid;
	}

	public ArrayList<TmstProjecthierarchytasksflow> getPrevTaskList() {
		return PrevTaskList;
	}

	public void setPrevTaskList(
			ArrayList<TmstProjecthierarchytasksflow> prevTaskList) {
		PrevTaskList = prevTaskList;
	}

	public String getAssignedtouserName() {
		return assignedtouserName;
	}

	public void setAssignedtouserName(String assignedtouserName) {
		this.assignedtouserName = assignedtouserName;
	}

	public String getTaskstakeholderName() {
		return taskstakeholderName;
	}

	public void setTaskstakeholderName(String taskstakeholderName) {
		this.taskstakeholderName = taskstakeholderName;
	}

	public String getTaskReferencedocname() {
		return taskReferencedocname;
	}

	public void setTaskReferencedocname(String taskReferencedocname) {
		this.taskReferencedocname = taskReferencedocname;
	}



	public String getCSV_nextTasksName() {
		return CSV_nextTasksName;
	}

	public void setCSV_nextTasksName(String tasksName) {
		CSV_nextTasksName = tasksName;
	}

	public ArrayList<TmstProjecthierarchytasksflow> getNextTaskList() {
		return NextTaskList;
	}

	public void setNextTaskList(
			ArrayList<TmstProjecthierarchytasksflow> nextTaskList) {
		NextTaskList = nextTaskList;
	}

	public ArrayList<TmEmployee> getAssignedUserList() {
		return assignedUserList;
	}

	public void setAssignedUserList(ArrayList<TmEmployee> assignedUserList) {
		this.assignedUserList = assignedUserList;
	}

	public String getCurrentTaskStatus() {
		return currentTaskStatus;
	}

	public void setCurrentTaskStatus(String currentTaskStatus) {
		this.currentTaskStatus = currentTaskStatus;
	}

	public Integer getRejectionAllowed() {
		return rejectionAllowed;
	}

	public void setRejectionAllowed(Integer rejectionAllowed) {
		this.rejectionAllowed = rejectionAllowed;
	}

	public ArrayList<TtrnProjecthierarchy> getValidPrevTaskList() {
		return validPrevTaskList;
	}

	public void setValidPrevTaskList(
			ArrayList<TtrnProjecthierarchy> validPrevTaskList) {
		this.validPrevTaskList = validPrevTaskList;
	}

	public int compareTo(TtrnProjecthierarchy o) {
		return this.currenttaskid.compareTo(o.currenttaskid);
	}

	public String getErrorLog() {
		return errorLog;
	}

	public void setErrorLog(String errorLog) {
		this.errorLog = errorLog;
	}

	public String[] getSelectedPrevTaskIds() {
		return selectedPrevTaskIds;
	}

	public void setSelectedPrevTaskIds(String[] selectedPrevTaskIds) {
		this.selectedPrevTaskIds = selectedPrevTaskIds;
	}

	public ArrayList getCurPrevTasks() {
		return curPrevTasks;
	}

	public void setCurPrevTasks(ArrayList curPrevTasks) {
		this.curPrevTasks = curPrevTasks;
	}

}
