package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.sql.Blob;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TtrnMeetingschedules generated by hbm2java
 */

public class TtrnMeetingschedules  implements java.io.Serializable {


    // Fields    

     private long meetingid;
     private TmMeetings tmMeetings;
     private String subject;
     private Date meetingdate;
     private String meetingdateString;
     private Date starttime;
     private Date endtime;
     private Blob attachment;
     private int isactive;
     private long cretaedby;
     private Date cretaeddate;
     private Long modifiedby;
     private Date modifieddate;
     private Blob attachment1;
     private Blob attachment2;
     private String filename;
     private String filename1;
     private String filename2;
  
     private TtrnProject ttrnProduct;
     private Long locationid;
     
     private String lblSubject_Short=null;
     
     ArrayList<TtrnMeetingattendies> attendies=null;
     private LocationDto location=new LocationDto();;
     
     private String starttimeString=null;
     private String endtimeString=null;

    // Constructors

    /** default constructor */
    public TtrnMeetingschedules() {
    }

	/** minimal constructor */
    public TtrnMeetingschedules(long meetingid, TmMeetings tmMeetings, String subject, Date meetingdate, Date starttime, Date endtime, int isactive, long cretaedby, Date cretaeddate) {
        this.meetingid = meetingid;
        this.tmMeetings = tmMeetings;
        this.subject = subject;
        this.meetingdate = meetingdate;
        this.starttime = starttime;
        this.endtime = endtime;
        this.isactive = isactive;
        this.cretaedby = cretaedby;
        this.cretaeddate = cretaeddate;
    }
    
    /** full constructor */
    public TtrnMeetingschedules(long meetingid, TmMeetings tmMeetings, String subject, Date meetingdate, Date starttime, Date endtime, Blob attachment, int isactive, long cretaedby, Date cretaeddate, Long modifiedby, Date modifieddate, Set ttrnMeetingattendieses,Blob attachment1,Blob attachment2,String filename,String filename1,String filename2) {
        this.meetingid = meetingid;
        this.tmMeetings = tmMeetings;
        this.subject = subject;
        this.meetingdate = meetingdate;
        this.starttime = starttime;
        this.endtime = endtime;
        this.attachment = attachment;
        this.attachment1 = attachment1;
        this.attachment2 = attachment2;
        this.filename = filename;
        this.filename1 = filename1;
        this.filename2 = filename2;
        this.isactive = isactive;
        this.cretaedby = cretaedby;
        this.cretaeddate = cretaeddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
      
    }
    

   
    // Property accessors

    public long getMeetingid() {
        return this.meetingid;
    }
    
    public void setMeetingid(long meetingid) {
        this.meetingid = meetingid;
    }

    public TmMeetings getTmMeetings() {
        return this.tmMeetings;
    }
    
    public void setTmMeetings(TmMeetings tmMeetings) {
        this.tmMeetings = tmMeetings;
    }

    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    public Date getMeetingdate() {
        return this.meetingdate;
    }
    
    public void setMeetingdate(Date meetingdate) {
        this.meetingdate = meetingdate;
    }

    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    public Blob getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(Blob attachment) {
        this.attachment = attachment;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public long getCretaedby() {
        return this.cretaedby;
    }
    
    public void setCretaedby(long cretaedby) {
        this.cretaedby = cretaedby;
    }

    public Date getCretaeddate() {
        return this.cretaeddate;
    }
    
    public void setCretaeddate(Date cretaeddate) {
        this.cretaeddate = cretaeddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

	public Blob getAttachment1() {
		return attachment1;
	}

	public void setAttachment1(Blob attachment1) {
		this.attachment1 = attachment1;
	}

	public Blob getAttachment2() {
		return attachment2;
	}

	public void setAttachment2(Blob attachment2) {
		this.attachment2 = attachment2;
	}

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getFilename1() {
		return filename1;
	}

	public void setFilename1(String filename1) {
		this.filename1 = filename1;
	}

	public String getFilename2() {
		return filename2;
	}

	public void setFilename2(String filename2) {
		this.filename2 = filename2;
	}

	
	public Long getLocationid() {
		return locationid;
	}

	public void setLocationid(Long locationid) {
		this.locationid = locationid;
	}

	public TtrnProject getTtrnProduct() {
		return ttrnProduct;
	}

	public void setTtrnProduct(TtrnProject ttrnProduct) {
		this.ttrnProduct = ttrnProduct;
	}

	public String getLblSubject_Short() {
		return lblSubject_Short;
	}

	public void setLblSubject_Short(String lblSubject_Short) {
		this.lblSubject_Short = lblSubject_Short;
	}

	public ArrayList<TtrnMeetingattendies> getAttendies() {
		return attendies;
	}

	public void setAttendies(ArrayList<TtrnMeetingattendies> attendies) {
		this.attendies = attendies;
	}

	public LocationDto getLocation() {
		return location;
	}

	public void setLocation(LocationDto location) {
		this.location = location;
	}

	public String getEndtimeString() {
		return endtimeString;
	}

	public void setEndtimeString(String endtimeString) {
		this.endtimeString = endtimeString;
	}

	public String getStarttimeString() {
		return starttimeString;
	}

	public void setStarttimeString(String starttimeString) {
		this.starttimeString = starttimeString;
	}

	public String getMeetingdateString() {
		return meetingdateString;
	}

	public void setMeetingdateString(String meetingdateString) {
		this.meetingdateString = meetingdateString;
	}

	
   







}
