package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TtrnProjectplrs generated by hbm2java
 */

public class TtrnProjectplrs  implements java.io.Serializable {


    // Fields    

     private long projectplrid;
     private TtrnProject ttrnProject;
     private Date plrstartdate;
     private Date plrenddate;
     private int isactive;
     private long createdby;
     private Date createddate;
     private Long modifiedby;
     private Date modifieddate;
     private Set ttrnProjectplrdetailses = new HashSet(0);


    // Constructors

    /** default constructor */
    public TtrnProjectplrs() {
    }

	/** minimal constructor */
    public TtrnProjectplrs(long projectplrid, TtrnProject ttrnProject, Date plrstartdate, int isactive, long createdby, Date createddate) {
        this.projectplrid = projectplrid;
        this.ttrnProject = ttrnProject;
        this.plrstartdate = plrstartdate;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
    }
    
    /** full constructor */
    public TtrnProjectplrs(long projectplrid, TtrnProject ttrnProject, Date plrstartdate, Date plrenddate, int isactive, long createdby, Date createddate, Long modifiedby, Date modifieddate, Set ttrnProjectplrdetailses) {
        this.projectplrid = projectplrid;
        this.ttrnProject = ttrnProject;
        this.plrstartdate = plrstartdate;
        this.plrenddate = plrenddate;
        this.isactive = isactive;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
        this.ttrnProjectplrdetailses = ttrnProjectplrdetailses;
    }
    

   
    // Property accessors

    public long getProjectplrid() {
        return this.projectplrid;
    }
    
    public void setProjectplrid(long projectplrid) {
        this.projectplrid = projectplrid;
    }

    public TtrnProject getTtrnProject() {
        return this.ttrnProject;
    }
    
    public void setTtrnProject(TtrnProject ttrnProject) {
        this.ttrnProject = ttrnProject;
    }

    public Date getPlrstartdate() {
        return this.plrstartdate;
    }
    
    public void setPlrstartdate(Date plrstartdate) {
        this.plrstartdate = plrstartdate;
    }

    public Date getPlrenddate() {
        return this.plrenddate;
    }
    
    public void setPlrenddate(Date plrenddate) {
        this.plrenddate = plrenddate;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }

    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Long getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public Set getTtrnProjectplrdetailses() {
        return this.ttrnProjectplrdetailses;
    }
    
    public void setTtrnProjectplrdetailses(Set ttrnProjectplrdetailses) {
        this.ttrnProjectplrdetailses = ttrnProjectplrdetailses;
    }
   








}
