package com.ibm.ioes.npd.hibernate.beans;
// Generated Dec 9, 2009 11:12:39 AM by Hibernate Tools 3.1.0.beta4

import java.sql.Blob;
import java.util.Date;


/**
 * TtrnProjectactiondocsId generated by hbm2java
 */

public class TtrnProjectactiondocsId  implements java.io.Serializable {


    // Fields    

     private int projectactiondocid;
     private long projectactionid;
     private Integer stageid;
     private Long taskid;
     private String docname;
     private Blob document;
     private String docmimetype;
     private Date docuploaddate;
     private Integer docuploadby;
     private int createdby;
     private Date createddate;
     private Integer modifiedby;
     private Date modifieddate;
     private int isactive;


    // Constructors

    /** default constructor */
    public TtrnProjectactiondocsId() {
    }

	/** minimal constructor */
    public TtrnProjectactiondocsId(int projectactiondocid, long projectactionid, int createdby, Date createddate, int isactive) {
        this.projectactiondocid = projectactiondocid;
        this.projectactionid = projectactionid;
        this.createdby = createdby;
        this.createddate = createddate;
        this.isactive = isactive;
    }
    
    /** full constructor */
    public TtrnProjectactiondocsId(int projectactiondocid, long projectactionid, Integer stageid, Long taskid, String docname, Blob document, String docmimetype, Date docuploaddate, Integer docuploadby, int createdby, Date createddate, Integer modifiedby, Date modifieddate, int isactive) {
        this.projectactiondocid = projectactiondocid;
        this.projectactionid = projectactionid;
        this.stageid = stageid;
        this.taskid = taskid;
        this.docname = docname;
        this.document = document;
        this.docmimetype = docmimetype;
        this.docuploaddate = docuploaddate;
        this.docuploadby = docuploadby;
        this.createdby = createdby;
        this.createddate = createddate;
        this.modifiedby = modifiedby;
        this.modifieddate = modifieddate;
        this.isactive = isactive;
    }
    

   
    // Property accessors

    public int getProjectactiondocid() {
        return this.projectactiondocid;
    }
    
    public void setProjectactiondocid(int projectactiondocid) {
        this.projectactiondocid = projectactiondocid;
    }

    public long getProjectactionid() {
        return this.projectactionid;
    }
    
    public void setProjectactionid(long projectactionid) {
        this.projectactionid = projectactionid;
    }

    public Integer getStageid() {
        return this.stageid;
    }
    
    public void setStageid(Integer stageid) {
        this.stageid = stageid;
    }

    public Long getTaskid() {
        return this.taskid;
    }
    
    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }

    public String getDocname() {
        return this.docname;
    }
    
    public void setDocname(String docname) {
        this.docname = docname;
    }

    public Blob getDocument() {
        return this.document;
    }
    
    public void setDocument(Blob document) {
        this.document = document;
    }

    public String getDocmimetype() {
        return this.docmimetype;
    }
    
    public void setDocmimetype(String docmimetype) {
        this.docmimetype = docmimetype;
    }

    public Date getDocuploaddate() {
        return this.docuploaddate;
    }
    
    public void setDocuploaddate(Date docuploaddate) {
        this.docuploaddate = docuploaddate;
    }

    public Integer getDocuploadby() {
        return this.docuploadby;
    }
    
    public void setDocuploadby(Integer docuploadby) {
        this.docuploadby = docuploadby;
    }

    public int getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TtrnProjectactiondocsId) ) return false;
		 TtrnProjectactiondocsId castOther = ( TtrnProjectactiondocsId ) other; 
         
		 return (this.getProjectactiondocid()==castOther.getProjectactiondocid())
 && (this.getProjectactionid()==castOther.getProjectactionid())
 && ( (this.getStageid()==castOther.getStageid()) || ( this.getStageid()!=null && castOther.getStageid()!=null && this.getStageid().equals(castOther.getStageid()) ) )
 && ( (this.getTaskid()==castOther.getTaskid()) || ( this.getTaskid()!=null && castOther.getTaskid()!=null && this.getTaskid().equals(castOther.getTaskid()) ) )
 && ( (this.getDocname()==castOther.getDocname()) || ( this.getDocname()!=null && castOther.getDocname()!=null && this.getDocname().equals(castOther.getDocname()) ) )
 && ( (this.getDocument()==castOther.getDocument()) || ( this.getDocument()!=null && castOther.getDocument()!=null && this.getDocument().equals(castOther.getDocument()) ) )
 && ( (this.getDocmimetype()==castOther.getDocmimetype()) || ( this.getDocmimetype()!=null && castOther.getDocmimetype()!=null && this.getDocmimetype().equals(castOther.getDocmimetype()) ) )
 && ( (this.getDocuploaddate()==castOther.getDocuploaddate()) || ( this.getDocuploaddate()!=null && castOther.getDocuploaddate()!=null && this.getDocuploaddate().equals(castOther.getDocuploaddate()) ) )
 && ( (this.getDocuploadby()==castOther.getDocuploadby()) || ( this.getDocuploadby()!=null && castOther.getDocuploadby()!=null && this.getDocuploadby().equals(castOther.getDocuploadby()) ) )
 && (this.getCreatedby()==castOther.getCreatedby())
 && ( (this.getCreateddate()==castOther.getCreateddate()) || ( this.getCreateddate()!=null && castOther.getCreateddate()!=null && this.getCreateddate().equals(castOther.getCreateddate()) ) )
 && ( (this.getModifiedby()==castOther.getModifiedby()) || ( this.getModifiedby()!=null && castOther.getModifiedby()!=null && this.getModifiedby().equals(castOther.getModifiedby()) ) )
 && ( (this.getModifieddate()==castOther.getModifieddate()) || ( this.getModifieddate()!=null && castOther.getModifieddate()!=null && this.getModifieddate().equals(castOther.getModifieddate()) ) )
 && (this.getIsactive()==castOther.getIsactive());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProjectactiondocid();
         result = 37 * result + (int) this.getProjectactionid();
         result = 37 * result + ( getStageid() == null ? 0 : this.getStageid().hashCode() );
         result = 37 * result + ( getTaskid() == null ? 0 : this.getTaskid().hashCode() );
         result = 37 * result + ( getDocname() == null ? 0 : this.getDocname().hashCode() );
         result = 37 * result + ( getDocument() == null ? 0 : this.getDocument().hashCode() );
         result = 37 * result + ( getDocmimetype() == null ? 0 : this.getDocmimetype().hashCode() );
         result = 37 * result + ( getDocuploaddate() == null ? 0 : this.getDocuploaddate().hashCode() );
         result = 37 * result + ( getDocuploadby() == null ? 0 : this.getDocuploadby().hashCode() );
         result = 37 * result + this.getCreatedby();
         result = 37 * result + ( getCreateddate() == null ? 0 : this.getCreateddate().hashCode() );
         result = 37 * result + ( getModifiedby() == null ? 0 : this.getModifiedby().hashCode() );
         result = 37 * result + ( getModifieddate() == null ? 0 : this.getModifieddate().hashCode() );
         result = 37 * result + this.getIsactive();
         return result;
   }   





}
