<%@taglib uri="http://struts.apache.org/tags-html" prefix="html"%>
<%@taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<%@taglib uri="http://struts.apache.org/tags-logic" prefix="logic"%>
<html:html>
<head>
<%
response.setContentType("application/vnd.ms-excel");
%>
</head>
<body>
<logic:present name="CustomerBaseReportInExcel" scope="request">
<% response.setHeader("content-Disposition","attachment;filename=CustomerBaseReport.xls"); %>
<table style="display:block;overflow:auto;vertical-align:top" width="99%" border="1" align="center" class="tab2" >
<tr><td colspan="46" align="left" style="font-size:10px"><strong>CUSTOMER BASE REPORT</strong></td></tr><tr><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Order No</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>External Id</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>External Account No</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Active Date</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Inactive Date</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Crm Account No</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>AccountNo</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Account Segment </b></td><%-- <td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Parent Id</b></td>--%><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill Fname</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill Company</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill Address1</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill Address2</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill Address3</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill City</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill State</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Account Manager</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Account Manager EmailId</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Account Manager Phone No</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Contact Person Phone(Contact1 Phone)</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill Zip</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Order Type</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Contact Person Name</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Contact Person Email</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Chairperson Name</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Chairperson Phone</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Chairperson Email</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Component Name</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Component Active Date</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Business Segment</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill Period</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Bill Frequency</b></td><td align="center" style="font-size:9px" bgcolor="#FF9255" ><b>Product Name</b></td></tr>
<logic:empty  name="CustomerBaseReportInExcel">
<tr align="center" ><td colspan="32" align="center"><b><font color="red">No Records Found</font></b></td></tr>
</logic:empty>
<logic:present name="CustomerBaseReportInExcel" scope="request">
<logic:notEmpty  name="CustomerBaseReportInExcel" scope="request">		
<logic:iterate id="row" name="CustomerBaseReportInExcel" indexId="recordId">
<tr><td><bean:write  name="row" property="orderNo"/></td><td><bean:write  name="row" property="fxSiId"/></td><td><bean:write  name="row" property="fx_external_acc_id"/></td><td><bean:write  name="row" property="activeDate"/></td><td><bean:write  name="row" property="inActiveDate"/></td><td><bean:write  name="row" property="crmACcountNO"/></td><td><bean:write  name="row" property="accountno"/></td><td><bean:write  name="row" property="accountSegment"/></td><%-- <td><bean:write  name="row" property="parent_name"/></td>--%><td><bean:write  name="row" property="billingFormatName"/></td><td><bean:write  name="row" property="billCompany"/></td><td><bean:write  name="row" property="billingAddress"/></td><td><bean:write  name="row" property="billing_address2"/></td><td><bean:write  name="row" property="billing_address"/></td><td><bean:write  name="row" property="billCity"/></td><td><bean:write  name="row" property="billState"/></td><td><bean:write  name="row" property="accountManager"/></td><td><bean:write  name="row" property="acmgrEmail"/></td><td><bean:write  name="row" property="accountMgrPhoneNo"/></td><td><bean:write  name="row" property="contact1_Phone"/></td><td><bean:write  name="row" property="billZip"/></td><td><bean:write  name="row" property="order_type"/></td><td><bean:write  name="row" property="contactName"/></td><td><bean:write  name="row" property="contactPersonEmail"/></td><td><bean:write  name="row" property="chairPersonName"/></td><td><bean:write  name="row" property="chairPersonPhone"/></td><td><bean:write  name="row" property="chairPersonEmail"/></td><td><bean:write  name="row" property="componentName"/></td><td><bean:write  name="row" property="componentActiveDate"/></td><td><bean:write  name="row" property="businessSegment"/></td><td><bean:write  name="row" property="bill_period"/></td><td><bean:write  name="row" property="frequencyName"/></td><td><bean:write  name="row" property="productName"/></td></tr>
</logic:iterate>
</logic:notEmpty>	
</logic:present>
</table>	
</logic:present>
</body>
</html:html>